### ISSUE TITLE
FoD ISO can not be downloaded with Windows Server vNext Preview - Build 17713

### ISSUE THREAD

**Issue by MasayukiOzawa** [MicrosoftDocs/windows-insider#10]
I'd like to try out the function of FoD with ver 17713, but there seems to be no ISO download link of FoD from 
https: //www.microsoft.com/en-us/software-download/windowsinsiderpreviewerver.
In Ver 17713, where can i download the FoD ISO from?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30f7de7e-c8cd-793d-6fb8-3345824f5914
* Version Independent ID: 4ea62ad0-9a4d-1456-be70-22a9a3f614fa
* Content: [What's new in the Windows Server 2019 Insider Preview Builds](https://docs.microsoft.com/en-us/windows-insider/at-work/whats-new-wip-at-work#failover-clustering-moving-clusters-between-domains)
* Content Source: [wip/at-work/Whats-new-wip-at-work.md](https://github.com/MicrosoftDocs/windows-insider/blob/master/wip/at-work/Whats-new-wip-at-work.md)
* Service: **wip-at-work**
* GitHub Login: @dawn.wood
* Microsoft Alias: **dawn.wood**

**Comment by dawnwood** [comment]
Hi MasayukiOzawa,
 We did not release the FOD with 17713 due to a problem with installation. It will be back with the next Insider release. 
Hope this helps.
