### ISSUE TITLE
Add Release Preview column to RS4 / RS5

### ISSUE THREAD

**Issue by hoyty76** [MicrosoftDocs/windows-insider#102]
There may only be one build but if there was ever a release preview build in RS4 / RS5 could you add it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa80910a-e655-34df-d26a-b094dd8702bb
* Version Independent ID: 83b90d10-f455-fee5-cf94-2698f1ac33d6
* Content: [Flight Hub](https://docs.microsoft.com/en-us/windows-insider/flight-hub/)
* Content Source: [wip/flight-hub/index.md](https://github.com/MicrosoftDocs/windows-insider/blob/master/wip/flight-hub/index.md)
* Service: **wip**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by BR77BE** [comment]
Release Preview ring for RS5 has received 18 builds which are not documented by Microsoft anywhere:
https://changewindows.org/build/redstone5/17763/pc

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@hoyty76  - Thank you for submitting feedback.

I will get this issue over to the Windows Insider writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by lizap** [comment]
Thanks for the feedback. We'll take it under advisement and add a release preview column when and if it makes sense. Thanks!
