### ISSUE TITLE
Build 18298" misspelt as "Bu8ild 18298

### ISSUE THREAD

**Issue by theterminator3000** [MicrosoftDocs/windows-insider#106]
https://docs.microsoft.com/en-us/windows-insider/at-home/whats-new-wip-at-home#start-menu-improvements-bu8ild-18298

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df65515f-272d-53f6-0740-d19784a517f0
* Version Independent ID: 83d9e436-c660-6203-3438-2f75b8b128f4
* Content: [What's new in the Windows 10 Insider Preview Builds (19H1)](https://docs.microsoft.com/en-us/windows-insider/at-home/whats-new-wip-at-home#feedback)
* Content Source: [wip/at-home/Whats-new-wip-at-home.md](https://github.com/MicrosoftDocs/windows-insider/blob/master/wip/at-home/Whats-new-wip-at-home.md)
* Service: **wip-at-home**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by lizap** [comment]
Thanks for raising this issue - just pushed a fix.
