### ISSUE TITLE
Image animation is missing

### ISSUE THREAD

**Issue by angww** [MicrosoftDocs/windows-insider#107]
In [Input Improvements](https://docs.microsoft.com/en-us/windows-insider/at-home/whats-new-wip-at-home#input-improvements-build-18272) the second image (gif) are not correct. Image animation is missing.

Image link: [image using the Hindi Phonetic keyboard](https://docs.microsoft.com/en-us/windows-insider/at-home/images/18272-image3.gif)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df65515f-272d-53f6-0740-d19784a517f0
* Version Independent ID: 83d9e436-c660-6203-3438-2f75b8b128f4
* Content: [What's new in the Windows 10 Insider Preview Builds (19H1)](https://docs.microsoft.com/en-us/windows-insider/at-home/whats-new-wip-at-home#improving-light-theme-build-18323)
* Content Source: [wip/at-home/Whats-new-wip-at-home.md](https://github.com/MicrosoftDocs/windows-insider/blob/master/wip/at-home/Whats-new-wip-at-home.md)
* Service: **wip-at-home**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by lizap** [comment]
Closing as fixed as I see only one image and it's animated. Please reopen if I'm in the wrong. Thanks!
