### ISSUE TITLE
20H1 Skip ahead build number typo?

### ISSUE THREAD

**Issue by Ry5ter** [MicrosoftDocs/windows-insider#108]
18836 not 18336 ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa80910a-e655-34df-d26a-b094dd8702bb
* Version Independent ID: 83b90d10-f455-fee5-cf94-2698f1ac33d6
* Content: [Flight Hub](https://docs.microsoft.com/en-us/windows-insider/flight-hub/)
* Content Source: [wip/flight-hub/index.md](https://github.com/MicrosoftDocs/windows-insider/blob/master/wip/flight-hub/index.md)
* Service: **wip**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by lizap** [comment]
Yep, that was a typo - we've fixed it. Thanks!

**Comment by Ry5ter** [comment]
Thanks 😁

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
