### ISSUE TITLE
Missing PDF

### ISSUE THREAD

**Issue by NazmusLabs** [MicrosoftDocs/windows-insider#109]
Clicking "Download PDF" yields in Microsoft Edge noting that the PDF is empty.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc12e690-19c5-ba46-530f-56b2e4f2bb33
* Version Independent ID: 237aec15-eb8f-78ed-086f-518b4ce554dd
* Content: [What's new in the Windows 10 Insider Preview Builds (RS5)](https://docs.microsoft.com/en-us/windows-insider/at-home/whats-new-wip-at-home-1809)
* Content Source: [wip/at-home/Whats-new-wip-at-home-1809.md](https://github.com/MicrosoftDocs/windows-insider/blob/master/wip/at-home/Whats-new-wip-at-home-1809.md)
* Service: **wip-at-home**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@NazmusLabs - Thank you for pointing this out.

I will get this issue over to the Windows Insider writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@lizap - I checked on the Download link and it redirects to a page with a message-"Error
Failed to load PDF document." Here's the Download link URL - **https://opdhsblobprod04.blob.core.windows.net/contents/8bbef6de52cc41879cccbe6cf3d0ddab/d98c1dd4008f04b2e9800998ecf8427e?sv=2015-04-05&sr=b&sig=9WZ8i3uvM78mrD%2F7SdlReXsfM6VgBbkFud3w80ZTOus%3D&st=2019-03-20T16%3A25%3A37Z&se=2019-03-21T16%3A35%3A37Z&sp=r**
Please let us know what is the correct URL link for this so a PR can be created or please advise on how to proceed with this. Thank you.

**Comment by mypil** [comment]
@lizap - I would like to follow up on this. Any updates?

**Comment by mypil** [comment]
@NazmusLabs - From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
