### ISSUE TITLE
Cmd default font size to small

### ISSUE THREAD

**Issue by adminjakab** [MicrosoftDocs/windows-insider#111]
Cmd default font size is to small. Please change it min. 16 size.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df65515f-272d-53f6-0740-d19784a517f0
* Version Independent ID: 83d9e436-c660-6203-3438-2f75b8b128f4
* Content: [What's new in the Windows 10 Insider Preview Builds (19H1)](https://docs.microsoft.com/en-us/windows-insider/at-home/whats-new-wip-at-home?MC=Windows&MC=Virtual&MC=Open&MC=OfficeO365&MC=MSAzure#feedback)
* Content Source: [wip/at-home/Whats-new-wip-at-home.md](https://github.com/MicrosoftDocs/windows-insider/blob/master/wip/at-home/Whats-new-wip-at-home.md)
* Service: **wip-at-home**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by FifoTheHein** [comment]
I change mine to font size 12 default. In my opinion 14 is too big, but its probably the best average for most users.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@adminjakab - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback on how to make the Windows Insider Program better. They keep a close tab on user feedback and it would be awesome if you could add your voice in User Voice **https://insider.windows.com/en-us/how-to-feedback/#submit-feedback-on-behalf-of-your-organization**
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
