### ISSUE TITLE
Use an unambiguous format for dates

### ISSUE THREAD

**Issue by robertwray** [MicrosoftDocs/windows-insider#112]
The dates that are being shown are in MM/DD/YYYY format which is primarily used in the United States.

Please switch dates to the YYYY-MM-DD (ISO:8601) format to remove ambiguity. Depending on where you are in the world 01/02/2020 is one of two dates, but 2020-02-01 isn't overloaded in this way.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa80910a-e655-34df-d26a-b094dd8702bb
* Version Independent ID: 83b90d10-f455-fee5-cf94-2698f1ac33d6
* Content: [Flight Hub](https://docs.microsoft.com/en-us/windows-insider/flight-hub/#feedback)
* Content Source: [wip/flight-hub/index.md](https://github.com/MicrosoftDocs/windows-insider/blob/master/wip/flight-hub/index.md)
* Service: **wip**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@robertwray - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback on how to make the Windows Insider Program better. They keep a close tab on user feedback and it would be awesome if you could add your voice in User Voice **https://insider.windows.com/en-us/how-to-feedback/#submit-feedback-on-behalf-of-your-organization**
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close

**Comment by robertwray** [comment]
I've raised a documentation issue because the date format displayed in the page is incorrect when viewed by pretty much anybody outside the United States and you've elected to direct me to documentation for submitting feedback as a member of an organisation? That doesn't even remotely track.

Thanks for wasting my time

**Comment by mypil** [comment]
@AndreaBarr - please assist to re-open this issue. thank you.

**Comment by mypil** [comment]
@robertwray - I've requested to re-open this issue so we can have this investigated. Thank you.

**Comment by mypil** [comment]
@lizap - need your insights on this issue since it is reported that the date format displayed in the page is incorrect when viewed by those outside the United States. Please advise on how to proceed to resolve this issue. Thank you.

**Comment by mypil** [comment]
@lizap - I would like to follow up on this. Do you have any updates? Thanks

**Comment by mypil** [comment]
@lizap - need your insights on this issue since it is reported that the date format displayed in the page is incorrect when viewed by those outside the United States. Please advise on how to proceed to resolve this issue. Thank you.

**Comment by mypil** [comment]
@lizap - I would like to follow up on this. Do you have any updates? Thanks

**Comment by IJMacD** [comment]
@mypil The issue isn't that dates are magically changing on the documentation page depending on where in the world they're viewed.

The issue is that 4/8/2019 is ambiguous and anyone outside the United States might read and understand it differently to those inside the US.

This GitHub issue asks that those writing documentation use the ISO Standard format of 2019-04-08 to reduce ambiguity internationally.

**Comment by mypil** [comment]
@IJMacD - Thanks for the additional feedback. I have coordinated with the doc owner @lizap to get her insights in getting the issue addressed. 

@lizap - I would like to follow up and get your insights on this issue. Thanks.

**Comment by mypil** [comment]
@lizap - I would like to follow up on this. Do you have any updates? Thanks

**Comment by lizap** [comment]
Hi, @IJMacD - thank you for the feedback. Right now we're following Microsoft style by using month/date/year format for the US content. The localized content should reflect the date standard for each locale. If it's not, please let me know. I'm sorry that this is causing confusion - given the purpose of the specific content (and the size of the table) I'm not able to switch to spelling out the dates, which is my only other option right now. (To use July 01, 2019 instead of 7/01/2019.( I will make sure your feedback informs future conversations on changes to the date format guidelines. 

Thanks, Liza

**Comment by robertwray** [comment]
Well, this sucks.

Changing from 07/01/2019 to 2019-01-07 takes the same amount of screen real estate and makes the format **unambiguous worldwide**. Not once in the original issue, or the comment by @IJMacD was it suggested that the long-form with the name of the month was moved to (which in and of itself would add further localisation complexity) so I'm not sure where that being the only option came from.

I'd also like to call out specifically:

> by using month/date/year format for the US content

This is content that is accessed by Windows Insiders all around the world. The vast majority of these (by country) do not use MM/DD/YYYY format for dates. According to https://en.wikipedia.org/wiki/Date_format_by_country usage of this format is vastly outstripped by others forms, of which the only unambiguous one is YYYYMMDD. 

Please think global.
