### ISSUE TITLE
Skip Ahead for Windows 10 (20H1) is most times out of date

### ISSUE THREAD

**Issue by it0056** [MicrosoftDocs/windows-insider#113]
I noticed that the release notes of the "Skip Ahead" 20H1 (and previously 19H1) links are always late. The blog-item does  exist only the Flighthub en Feedback hub doesn't have a link/content item.. This makes it harder to find the corresponding release notes to decide if you're gonna install this release. Please automate this.. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa80910a-e655-34df-d26a-b094dd8702bb
* Version Independent ID: 83b90d10-f455-fee5-cf94-2698f1ac33d6
* Content: [Flight Hub](https://docs.microsoft.com/en-us/windows-insider/flight-hub/#feedback)
* Content Source: [wip/flight-hub/index.md](https://github.com/MicrosoftDocs/windows-insider/blob/master/wip/flight-hub/index.md)
* Product: **w10**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@it0056 - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback on how to make the Windows Insider Program better. They keep a close tab on user feedback and it would be awesome if you could add your voice in User Voice **https://insider.windows.com/en-us/how-to-feedback/#submit-feedback-on-behalf-of-your-organization**
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
