### ISSUE TITLE
The table below the "Next feature update for Windows 10 (19H1)" heading isn't rendering correctly

### ISSUE THREAD

**Issue by iadgovuser1** [MicrosoftDocs/windows-insider#119]
The table below the "Next feature update for Windows 10 (19H1)" heading isn't rendering correctly

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa80910a-e655-34df-d26a-b094dd8702bb
* Version Independent ID: 83b90d10-f455-fee5-cf94-2698f1ac33d6
* Content: [Flight Hub](https://docs.microsoft.com/en-us/windows-insider/flight-hub/)
* Content Source: [wip/flight-hub/index.md](https://github.com/MicrosoftDocs/windows-insider/blob/master/wip/flight-hub/index.md)
* Product: **w10**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by IdmFoundInHim** [comment]
![Screenshot_20190403-153336](https://user-images.githubusercontent.com/30935172/55507683-2a4dd280-5626-11e9-9dbd-aa1b552f8bba.jpg)
It looks like a merge conflict.

**Comment by iadgovuser1** [comment]
My guess is these changes need to be made at a minimum.

L53 change
`|18361|[3/19/2019](https://blogs.windows.com/windowsexperience/2019/03/19/announcing-windows-10-insider-preview-build-18361/#mHcv6FGsAlkBB8Wl.97)`
to
`|18361|[3/19/2019](https://blogs.windows.com/windowsexperience/2019/03/19/announcing-windows-10-insider-preview-build-18361/#mHcv6FGsAlkBB8Wl.97)||||||`

L54 change
`|18358|[3/15/2019](https://blogs.windows.com/windowsexperience/2019/03/15/announcing-windows-10-insider-preview-build-18358/#Whpph8JpuKtARpqh.97)|||||||`
to
`|18358|[3/15/2019](https://blogs.windows.com/windowsexperience/2019/03/15/announcing-windows-10-insider-preview-build-18358/#Whpph8JpuKtARpqh.97)||||||`

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@iadgovuser1 - Thank you for submitting feedback.

I will get this issue over to the Windows Insider writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@iadgovuser1 - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by iadgovuser1** [comment]
Looks fixed to me. Thanks!
