### ISSUE TITLE
Locked out 

### ISSUE THREAD

**Issue by unjumpednewbhacker** [MicrosoftDocs/windows-insider#120]
Did a reset and been locked out ever since... I don't recall creating an unlock code. PLEASE HELP ME!!!

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@unjumpednewbhacker - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows Insider Program:  **https://techcommunity.microsoft.com/t5/Windows-Insider-Program/bd-p/WindowsInsiderProgram**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by unjumpednewbhacker** [comment]
Well Myp.. This issue has surpassed asap resolve stages and circled back as would an animal chasing its tail. No ticket served as a means of any forward progress what so ever. This is the outcome I suppose, I entertained some wacky fix sugestions from a few known bulltube scammers but mostly I operate by a trial and error system working forward and backward. I have learned a lot however the process produces no fruit. I like my new chromebook but I cant seem to accept defeat by what turnes out to me to be such an unrelyable and disappointing system. More to come as per your request, until then, good day sir.

**Comment by mypil** [comment]
@unjumpednewbhacker - Sorry to hear that you are having issues. Please understand that this site is a product documentation site and not a support nor a feature request site.

As such, the feedback section here is intended for feedback that improves the content in the Microsoft documentation and not intended for user feedback on product features nor troubleshooting.

For user feedback on product feature requests, you can submit via User Voice - **https://insider.windows.com/en-us/how-to-feedback/#submit-feedback-on-behalf-of-your-organization**. I know the product teams are always looking for user feedback on how to make the Windows Insider Program better. You might find others have made a similar request that you can add to, or you can open a new one.

For troubleshooting, you can visit **support.microsoft.com**, **answers.microsoft.com** or open a support ticket- **https://techcommunity.microsoft.com/t5/Windows-Insider-Program/bd-p/WindowsInsiderProgram**.

I hope this gets you pointed in the right direction. Thank you.

**Comment by mypil** [comment]
@officedocsbot close
