### ISSUE TITLE
[LOC] "高度な設定 _gt メディアの自動再生" needs to be replaced with "高度な設定 > メディアの自動再生"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-insider#123]
https://docs.microsoft.com/ja-jp/windows-insider/at-home/whats-new-wip-at-home-1809

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: dc12e690-19c5-ba46-530f-56b2e4f2bb33
* Version Independent ID: 237aec15-eb8f-78ed-086f-518b4ce554dd
* Content: [新機能、Windows 10 Insider Preview ビルド (RS5)](https://docs.microsoft.com/ja-jp/windows-insider/at-home/whats-new-wip-at-home-1809#feedback)
* Content Source: [wip/at-home/Whats-new-wip-at-home-1809.md](https://github.com/MicrosoftDocs/windows-insider/blob/master/wip/at-home/Whats-new-wip-at-home-1809.md)
* Product: **w10**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@hyoshioka0128 - Thank you for submitting feedback.

I will get this issue over to the Windows Insider writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@officedocsbot add label localization

**Comment by mypil** [comment]
@dongmicro - Can you please assist with this Translation (Localization) issue?

**Comment by mypil** [comment]
@officedocsbot assign @dongmicro

**Comment by mypil** [comment]
@dongmicro - I would like to follow up on this. Do you have any updates?

Thank you.

**Comment by mypil** [comment]
@dongmicro - We would like to follow up. Kindly assist to provide updates on the status of all these Translation (Localization) issues in the Windows Insider repo. Thank you.

**Comment by mypil** [comment]
Referencing https://github.com/MicrosoftDocs/windows-insider/issues/145#issuecomment-497848599  for the status update of all these Translation (Localization) issues.

**Comment by dongmicro** [comment]
MT will be re-Run against the pages and hope most the problem will be fixed after the MT bug got fixed. After the MT re-Run against the pages if the problem is still there we will see what needs to be done.

**Comment by mypil** [comment]
@dongmicro - Do you have any updates on the status of these Translation (Localization) issues?

**Comment by mypil** [comment]
@dongmicro - Any updates on this? Which ones has been fixed already? Please assist to give us updates so we can close these issues. Thank you.

**Comment by mypil** [comment]
@officedocsbot unassign @dongmicro 
@officedocsbot assign @MollyMalone

**Comment by mypil** [comment]
@hyoshioka0128 - Can you please validate and confirm if all the Translation (Localization) issues that you opened have been resolved? 

The latest update we received is that the repos were just migrated so this may have already fixed the MT issues.  Thank you!

**Comment by hyoshioka0128** [comment]
Hi, @mypil.
#123 list is Verified.
Thank you.

**Comment by mypil** [comment]
@officedocsbot assign @TinaMcN

**Comment by TinaMcN** [comment]
@hyoshioka0128 フィードバックをありがとうございました。 これは MT ツールの問題です。 私はツールの所有者に問題を報告しました。  この問題がすぐに解決されるとは思いません。 修正が必要になったときに更新します。(Thank you for the feedback.  This is a problem with the MT tool.  I have reported the problem to the tool owners.   I don't expect this issue to be fixed quickly.  I will update when we have a fix.)

**Comment by TinaMcN** [comment]
@hyoshioka0128 記事は現在、人間が翻訳されています。 修正済みであることを確認してください。 フィードバックをありがとう。(The article is now human translated.  Please verify that it is fixed.  Thanks again for the feedback.)

**Comment by hyoshioka0128** [comment]
@TinaMcN - Corrected.
Closed #123.
Thanks.
