### ISSUE TITLE
[LOC] Showing "![新しい設定] ページ](images/18272-app2.png "The Settings page in Snip & Sketch")"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-insider#131]
https://docs.microsoft.com/ja-jp/windows-insider/at-home/whats-new-apps-19h1

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: be459bcb-4f00-035e-758b-f96e6196e7f3
* Version Independent ID: ac56f8ae-3436-3737-0fff-7030ad2bb0e5
* Content: [Windows 10 Insider Preview ビルド (19 H 1) の新規および更新されたアプリ](https://docs.microsoft.com/ja-jp/windows-insider/at-home/whats-new-apps-19h1)
* Content Source: [wip/at-home/whats-new-apps-19h1.md](https://github.com/MicrosoftDocs/windows-insider/blob/master/wip/at-home/whats-new-apps-19h1.md)
* Product: **w10**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@hyoshioka0128 - Thank you for submitting feedback.

I will get this issue over to the Windows Insider writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@officedocsbot add label localization

**Comment by mypil** [comment]
@dongmicro - Can you please assist with this Translation (Localization) issue?

**Comment by mypil** [comment]
@officedocsbot assign @dongmicro

**Comment by mypil** [comment]
@dongmicro - I would like to follow up on this. Do you have any updates?

Thank you.

**Comment by mypil** [comment]
@officedocsbot unassign @dongmicro 
@officedocsbot assign @MollyMalone

**Comment by hyoshioka0128** [comment]
Hi, @mypil .
Fixed.
Close #131
