### ISSUE TITLE
[LOC] Showing "アプリ _gt 付箋****カテゴリ"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-insider#132]
https://docs.microsoft.com/ja-jp/windows-insider/at-home/whats-new-apps-19h1

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: be459bcb-4f00-035e-758b-f96e6196e7f3
* Version Independent ID: ac56f8ae-3436-3737-0fff-7030ad2bb0e5
* Content: [Windows 10 Insider Preview ビルド (19 H 1) の新規および更新されたアプリ](https://docs.microsoft.com/ja-jp/windows-insider/at-home/whats-new-apps-19h1)
* Content Source: [wip/at-home/whats-new-apps-19h1.md](https://github.com/MicrosoftDocs/windows-insider/blob/master/wip/at-home/whats-new-apps-19h1.md)
* Product: **w10**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@hyoshioka0128 - Thank you for submitting feedback.

I will get this issue over to the Windows Insider writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@officedocsbot add label localization

**Comment by mypil** [comment]
@dongmicro - Can you please assist with this Translation (Localization) issue?

**Comment by mypil** [comment]
@officedocsbot assign @dongmicro

**Comment by mypil** [comment]
@officedocsbot unassign @dongmicro 
@officedocsbot assign @MollyMalone

**Comment by hyoshioka0128** [comment]
Hi, @mypil .
#132 is not Fixed.
ja-jp:https://docs.microsoft.com/ja-jp/windows-insider/at-home/whats-new-apps-19h1
![whats-new-apps-19h1_j1](https://user-images.githubusercontent.com/40815708/61788557-526b7680-ae4d-11e9-899e-900ca1e51ea3.png)

en-us:https://docs.microsoft.com/en-us/windows-insider/at-home/whats-new-apps
![whats-new-apps_e](https://user-images.githubusercontent.com/40815708/61788580-5f886580-ae4d-11e9-8def-59af94559343.png)

**Comment by mypil** [comment]
@MollyMalone - Issue is not fixed yet. Can you please check and assist with this?

Thank you.

**Comment by mypil** [comment]
@officedocsbot assign @TinaMcN

**Comment by TinaMcN** [comment]
私は人間の翻訳のためにこの記事を送った。 約2週間かかります。 (I sent this article to be human translated.  It should take approximately 2 weeks.)

**Comment by mypil** [comment]
@TinaMcN - Do you have any updates on the status of this? 

Thank you.

**Comment by TinaMcN** [comment]
@hyoshioka0128 記事は現在、人間が翻訳されています。 修正済みであることを確認してください。 フィードバックのおかげで再び (The article is now human translated.  Please verify that it is fixed.  Thanks again for the feedback)

**Comment by mypil** [comment]
@hyoshioka0128 - Kindly check and validate if issue has been resolved. Thank you.

**Comment by hyoshioka0128** [comment]
@TinaMcN @mypil - Corrected.
Closed #132.
Thanks.
