### ISSUE TITLE
[LOC] "__Settings>Updates & セキュリティ__" needs to be replaced with "設定 > 更新とセキュリティ"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-insider#133]
https://docs.microsoft.com/ja-jp/windows-insider/at-home/rings

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: e28bc5ad-1ad7-fd61-1194-54d41a6e0035
* Version Independent ID: 66f14d63-749c-7ea9-80d5-eae5dfb1df8e
* Content: [リングについて](https://docs.microsoft.com/ja-jp/windows-insider/at-home/rings)
* Content Source: [wip/at-home/rings.md](https://github.com/MicrosoftDocs/windows-insider/blob/master/wip/at-home/rings.md)
* Product: **w10**
* GitHub Login: @cdmm12
* Microsoft Alias: **v-colinmit**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@officedocsbot add label localization

**Comment by mypil** [comment]
@hyoshioka0128 - Thank you for submitting feedback.

I will get this issue over to the Windows Insider writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@officedocsbot assign @dongmicro

**Comment by mypil** [comment]
@dongmicro - Can you please assist with this Translation (Localization) issue?

**Comment by mypil** [comment]
@dongmicro - I would like to follow up on this. Do you have any updates?

Thank you.

**Comment by mypil** [comment]
@officedocsbot unassign @dongmicro 
@officedocsbot assign @MollyMalone

**Comment by hyoshioka0128** [comment]
Hi, @mypil .
#133 is not Fixed.
![rings_j](https://user-images.githubusercontent.com/40815708/61788013-066c0200-ae4c-11e9-96c3-c2ade6dd16b1.png)

**Comment by mypil** [comment]
@MollyMalone - Issue is not fixed yet. Can you please check and assist with this?

Thank you.

**Comment by mypil** [comment]
@officedocsbot assign @TinaMcN

**Comment by TinaMcN** [comment]
私は人間の翻訳のためにこの記事を送った。 約2週間かかります。 (I sent this article to be human translated.  It should take approximately 2 weeks.)

**Comment by mypil** [comment]
@TinaMcN - Do you have any updates on the status of this? 

Thank you.

**Comment by TinaMcN** [comment]
@hyoshioka0128 記事は現在、人間が翻訳されています。 修正済みであることを確認してください。 フィードバックのおかげで再び (The article is now human translated.  Please verify that it is fixed.  Thanks again for the feedback)

**Comment by TinaMcN** [comment]
記事は現在、人間が翻訳されています。 修正済みであることを確認してください。 フィードバックをありがとう。(The article is now human translated.  Please verify that it is fixed.  Thanks again for the feedback.)

**Comment by hyoshioka0128** [comment]
@TinaMcN - Corrected.
Closed #133.
Thanks.
