### ISSUE TITLE
[LOC] "__設定 _gt 更新 & セキュリティ _gt ライセンス認証__" needs to be replaced with "設定 > 更新とセキュリティ > ライセンス認証"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-insider#135]
https://docs.microsoft.com/ja-jp/windows-insider/at-home/troubleshooting

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: f86ee4af-4d0d-d880-3ca1-7282448fc43d
* Version Independent ID: 0a951de6-a0f3-c00f-41fe-482d1453240d
* Content: [トラブルシューティング](https://docs.microsoft.com/ja-jp/windows-insider/at-home/troubleshooting)
* Content Source: [wip/at-home/troubleshooting.md](https://github.com/MicrosoftDocs/windows-insider/blob/master/wip/at-home/troubleshooting.md)
* Product: **w10**
* GitHub Login: @cdmm12
* Microsoft Alias: **v-colinmit**

**Comment by mypil** [comment]
@officedocsbot assign @mypil
@officedocsbot add label localization

**Comment by mypil** [comment]
@hyoshioka0128 - Thank you for submitting feedback.

I will get this issue over to the Windows Insider writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@officedocsbot assign @dongmicro

**Comment by mypil** [comment]
@dongmicro - Can you please assist with this Translation (Localization) issue?

**Comment by mypil** [comment]
@dongmicro - I would like to follow up on this. Do you have any updates?

Thank you.

**Comment by mypil** [comment]
@officedocsbot unassign @dongmicro 
@officedocsbot assign @MollyMalone

**Comment by mypil** [comment]
@officedocsbot assign @TinaMcN

**Comment by TinaMcN** [comment]
私は人間の翻訳のためにこの記事を送った。 約2週間かかります。 (I sent this article to be human translated.  It should take approximately 2 weeks.)

**Comment by mypil** [comment]
@TinaMcN - Do you have any updates on the status of this? 

Thank you.

**Comment by TinaMcN** [comment]
@hyoshioka0128 記事は現在、人間が翻訳されています。 修正済みであることを確認してください。 フィードバックのおかげで再び (The article is now human translated.  Please verify that it is fixed.  Thanks again for the feedback)

**Comment by hyoshioka0128** [comment]
@TinaMcN - Corrected.
Closed #135.
Thanks.
