### ISSUE TITLE
Broken link "https://www.microsoft.com/store/apps/9NCTDW2W1BH8"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-insider#138]
https://docs.microsoft.com/ja-jp/windows-insider/at-home/whats-new-wip-at-home-19h1

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: b4599727-0163-9857-ce15-a2c82be9e936
* Version Independent ID: 22838d16-6ebf-280f-ed96-61a061d4b4a3
* Content: [新機能、Windows 10 Insider Preview ビルド (19 H 1)](https://docs.microsoft.com/ja-jp/windows-insider/at-home/whats-new-wip-at-home-19h1)
* Content Source: [wip/at-home/Whats-new-wip-at-home-19h1.md](https://github.com/MicrosoftDocs/windows-insider/blob/master/wip/at-home/Whats-new-wip-at-home-19h1.md)
* Product: **w10**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by mypil** [comment]
@officedocsbot assign @mypil
@officedocsbot add label localization

**Comment by mypil** [comment]
@hyoshioka0128 - Thank you for submitting feedback.

I will get this issue over to the Windows Insider writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@officedocsbot assign @dongmicro

**Comment by mypil** [comment]
@dongmicro - Can you please assist with this Translation (Localization) issue?

**Comment by mypil** [comment]
@dongmicro - I would like to follow up on this. Do you have any updates?

Thank you.

**Comment by mypil** [comment]
@officedocsbot unassign @dongmicro 
@officedocsbot assign @MollyMalone

**Comment by hyoshioka0128** [comment]
Hi, @mypil .
#138 is not Fixed.
![whats-new-wip-at-home-19h1_j2](https://user-images.githubusercontent.com/40815708/61786855-8cd31480-ae49-11e9-962d-58d085b1b308.png)

**Comment by mypil** [comment]
@MollyMalone - Issue is not fixed yet. Can you please check and assist with this?

Thank you.

**Comment by mypil** [comment]
@officedocsbot assign @TinaMcN

**Comment by mypil** [comment]
@TinaMcN - Do you have any updates on the latest progress of this?

**Comment by TinaMcN** [comment]
I notice that the English version of this page redirects to a newer page (https://docs.microsoft.com/en-us/windows-insider/at-home/whats-new-wip-at-home-1903).  Investigating...

**Comment by mypil** [comment]
@TinaMcN - Do you have any updates on the progress of the investigation?

Thank you.

**Comment by TinaMcN** [comment]
https://docs.microsoft.com/ja-jp/windows-insider/at-home/whats-new-wip-at-home-1903 has been sent for human translation which should fix the issue.

**Comment by mypil** [comment]
@TinaMcN - Do you have any updates on this?

Thank you.

**Comment by TinaMcN** [comment]
@hyoshioka0128 記事は現在、人間翻訳されており、問題は修正されているようです。 修正済みであることを確認してください。 フィードバックをありがとうございました。
(The article is now human translated and the issue appears to be fixed.  Please verify that it is fixed.  Thanks again for the feedback.)

**Comment by hyoshioka0128** [comment]
@TinaMcN  - Fixed.
Closed #138
Thanks.
