### ISSUE TITLE
Broken link "https://account.xbox.comXbox"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-insider#139]
https://docs.microsoft.com/ja-jp/windows-insider/at-home/whats-new-wip-at-home-19h1

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: b4599727-0163-9857-ce15-a2c82be9e936
* Version Independent ID: 22838d16-6ebf-280f-ed96-61a061d4b4a3
* Content: [新機能、Windows 10 Insider Preview ビルド (19 H 1)](https://docs.microsoft.com/ja-jp/windows-insider/at-home/whats-new-wip-at-home-19h1)
* Content Source: [wip/at-home/Whats-new-wip-at-home-19h1.md](https://github.com/MicrosoftDocs/windows-insider/blob/master/wip/at-home/Whats-new-wip-at-home-19h1.md)
* Product: **w10**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by mypil** [comment]
@officedocsbot assign @mypil @dongmicro 
@officedocsbot add label localization

**Comment by mypil** [comment]
@officedocsbot assign @dongmicro

**Comment by mypil** [comment]
@dongmicro - Can you please assist with this Translation (Localization) issue?

**Comment by mypil** [comment]
@dongmicro - I would like to follow up on this. Do you have any updates?

Thank you.

**Comment by mypil** [comment]
@officedocsbot unassign @dongmicro 
@officedocsbot assign @MollyMalone

**Comment by hyoshioka0128** [comment]
Hi, @mypil .
#139 is not Fixed.
![whats-new-wip-at-home-19h1_](https://user-images.githubusercontent.com/40815708/61786729-509fb400-ae49-11e9-8988-dc410b265784.png)

**Comment by mypil** [comment]
@MollyMalone - Issue is not fixed yet. Can you please check and assist with this?

Thank you.

**Comment by mypil** [comment]
@officedocsbot assign @TinaMcN

**Comment by mypil** [comment]
@TinaMcN - Do you have any updates on the latest progress of this?

**Comment by TinaMcN** [comment]
フィードバックをありがとうございました。 記事は機械翻訳されました。 私は人間の翻訳のためにそれを送った。 翻訳が完了するまでに最大4週間かかります。 (Thank you for the feedback.  The article was machine translated.  I sent it for human translation.  It will take up to 4 weeks to complete the translation.)

**Comment by mypil** [comment]
@hyoshioka0128 - Please check and confirm if issue is fixed. Thank you.

問題が修正されたかどうかを確認してください。 ありがとうございました。

**Comment by TinaMcN** [comment]
この記事はまだ機械翻訳です。 私は、人間翻訳版がいつ準備ができているかのステータスをローカリゼーションベンダーに確認しています。 (This article is still machine translated.  I am checking with the localization vendor for status on when the human translated version will be ready.)

**Comment by mypil** [comment]
@TinaMcN - Do you have any updates on this?

Thank you.

**Comment by TinaMcN** [comment]
@hyoshioka0128 記事は現在、人間が翻訳されています。 問題が解決したことを確認してください。 フィードバックをありがとう。
(The article is now human translated.  Please verify that the issue is fixed.  Thanks again for the feedback.)

**Comment by mypil** [comment]
@hyoshioka0128 - Please check and confirm if issue is fixed. Thank you.

問題が修正されたかどうかを確認してください。 ありがとうございました。

**Comment by hyoshioka0128** [comment]
@TinaMcN  @mypil - Closed #139 
Close because there is no corresponding content.
Redirected from "/whats-new-wip-at-home-19h1" to "/whats-new-wip-at-home-1903".
Thanks.
