### ISSUE TITLE
"正味の使用" needs to be replaced with "ネット利用"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-insider#141]
English: "Use net use, or some other method, to connect to the location of the FoD ISO."
Japanese: "FoD ISOの場所に接続するには、ネット利用などの方法を使用します。"

https://docs.microsoft.com/ja-jp/windows-insider/at-work/whats-new-wip-at-work-1809

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 350df361-e28b-9dc0-82fe-bccafe7aa2a8
* Version Independent ID: 5aa65b84-085d-51f0-abf9-c20435767b91
* Content: [新機能、Windows Server 2019 Insider Preview ビルド](https://docs.microsoft.com/ja-jp/windows-insider/at-work/whats-new-wip-at-work-1809)
* Content Source: [wip/at-work/Whats-new-wip-at-work-1809.md](https://github.com/MicrosoftDocs/windows-insider/blob/master/wip/at-work/Whats-new-wip-at-work-1809.md)
* Product: **w10**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@officedocsbot add label localization

**Comment by mypil** [comment]
@officedocsbot assign @dongmicro

**Comment by mypil** [comment]
@dongmicro - Can you please assist with this Translation (Localization) issue?

**Comment by mypil** [comment]
@dongmicro - I would like to follow up on this. Do you have any updates?

Thank you.

**Comment by mypil** [comment]
@officedocsbot unassign @dongmicro 
@officedocsbot assign @MollyMalone

**Comment by hyoshioka0128** [comment]
Hi, @mypil .
#141 is not Fixed.
ja-jp:
![whats-new-wip-at-work-1809_j3](https://user-images.githubusercontent.com/40815708/61605495-b725a600-ac80-11e9-8b0b-e7edba2a7e8e.png)

en-us:
![whats-new-wip-at-work-1809_e3](https://user-images.githubusercontent.com/40815708/61605497-bd1b8700-ac80-11e9-9e32-63f1834dd7b8.png)

**Comment by mypil** [comment]
@MollyMalone - Can you please assist with this issue? 

Thank you.

**Comment by mypil** [comment]
@officedocsbot assign @TinaMcN

**Comment by TinaMcN** [comment]
@hyoshioka0128 フィードバックをありがとうございました。 記事は機械翻訳されました。 私は人間の翻訳のためにそれを送った。 完了までに数週間かかる場合があります。(Thank you for the feedback.  The article was machine translated.  I sent it for human translation.  This may take a few weeks to complete.)

**Comment by mypil** [comment]
@hyoshioka0128 - Please check and confirm if issue is fixed. Thank you.

問題が修正されたかどうかを確認してください。 ありがとうございました。

**Comment by TinaMcN** [comment]
この記事はまだ機械翻訳です。 私は、人間翻訳版がいつ準備ができているかのステータスをローカリゼーションベンダーに確認しています。 (This article is still machine translated.  I am checking with the localization vendor for status on when the human translated version will be ready.)

**Comment by mypil** [comment]
@TinaMcN - Do you have any updates on this?

Thank you.

**Comment by TinaMcN** [comment]
私は人間の翻訳のためにこの記事を送った。 約2週間かかります。 (I sent this article to be human translated.  It should take approximately 2 weeks.)

**Comment by TinaMcN** [comment]
@hyoshioka0128 記事は現在、人間が翻訳されています。 修正済みであることを確認してください。 フィードバックのおかげで再び (The article is now human translated.  Please verify that it is fixed.  Thanks again for the feedback)

**Comment by hyoshioka0128** [comment]
@TinaMcN - Corrected.
Closed #141.
Thanks.
