### ISSUE TITLE
Broken link "https://aka.ms/windowscontainer "

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-insider#144]
https://docs.microsoft.com/ja-jp/windows-insider/at-work/whats-new-wip-at-work-1809

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 350df361-e28b-9dc0-82fe-bccafe7aa2a8
* Version Independent ID: 5aa65b84-085d-51f0-abf9-c20435767b91
* Content: [新機能、Windows Server 2019 Insider Preview ビルド](https://docs.microsoft.com/ja-jp/windows-insider/at-work/whats-new-wip-at-work-1809)
* Content Source: [wip/at-work/Whats-new-wip-at-work-1809.md](https://github.com/MicrosoftDocs/windows-insider/blob/master/wip/at-work/Whats-new-wip-at-work-1809.md)
* Product: **w10**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@officedocsbot add label localization

**Comment by mypil** [comment]
@officedocsbot assign @dongmicro

**Comment by mypil** [comment]
@dongmicro - Can you please assist with this Translation (Localization) issue?

**Comment by mypil** [comment]
@dongmicro - I would like to follow up on this. Do you have any updates?

Thank you.

**Comment by mypil** [comment]
@officedocsbot unassign @dongmicro 
@officedocsbot assign @MollyMalone

**Comment by hyoshioka0128** [comment]
Hi, @mypil .
#144 is not Fixed.
![whats-new-wip-at-work-1809_j1](https://user-images.githubusercontent.com/40815708/61593016-34b3cc80-ac15-11e9-897f-dd872d8b6d7f.png)

**Comment by mypil** [comment]
@MollyMalone - Can you please assist with this issue? 

Thank you.

**Comment by mypil** [comment]
@officedocsbot assign @TinaMcN

**Comment by mypil** [comment]
@TinaMcN - Do you have any updates on the latest progress of this?

**Comment by TinaMcN** [comment]
フィードバックをありがとうございました。 記事は機械翻訳されました。 私は人間の翻訳のためにそれを送った。 翻訳が完了するまでに最大4週間かかります。 (Thank you for the feedback.  The article was machine translated.  I sent it for human translation.  It will take up to 4 weeks to complete the translation.)

**Comment by mypil** [comment]
@hyoshioka0128 - Please check and confirm if issue is fixed. Thank you.

問題が修正されたかどうかを確認してください。 ありがとうございました。

**Comment by TinaMcN** [comment]
この記事はまだ機械翻訳です。 私は、人間翻訳版がいつ準備ができているかのステータスをローカリゼーションベンダーに確認しています。 (This article is still machine translated.  I am checking with the localization vendor for status on when the human translated version will be ready.)

**Comment by mypil** [comment]
@TinaMcN - Do you have any updates on this?

Thank you.

**Comment by TinaMcN** [comment]
私は人間の翻訳のためにこの記事を送った。 約2週間かかります。 (I sent this article to be human translated.  It should take approximately 2 weeks.)

**Comment by mypil** [comment]
@TinaMcN - Do you have any updates if this issue has been fixed?

Thank you.

**Comment by TinaMcN** [comment]
@mypil the bug was incorrectly assigned.  I reassigned to the localization vendors who will hopefully fix it soon.

**Comment by TinaMcN** [comment]
@hyoshioka0128 これで問題が修正されました。 フィードバックをありがとう。 (The issue has now been fixed.  Thanks again for the feedback.)

**Comment by hyoshioka0128** [comment]
@TinaMcN - Corrected.
Closed #144.
Thanks.
