### ISSUE TITLE
[LOC]"_gt 設定 gt 更新 & セキュリティ gt Windows Insider Program の開始" needs to be replaced with "設定 > 更新とセキュリティ > Windows Insider Program"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-insider#145]
https://docs.microsoft.com/ja-jp/windows-insider/at-home/get-started

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: ecfeb071-5a62-8103-e97b-498966b9beb3
* Version Independent ID: 88b688a6-d675-d52a-44f5-6a5ff51f5fb6
* Content: [Windows 10 Insider Preview ビルドの概要](https://docs.microsoft.com/ja-jp/windows-insider/at-home/get-started)
* Content Source: [wip/at-home/get-started.md](https://github.com/MicrosoftDocs/windows-insider/blob/master/wip/at-home/get-started.md)
* Product: **w10**
* GitHub Login: @cdmm12
* Microsoft Alias: **v-colinmit**

**Comment by mypil** [comment]
@officedocsbot assign @mypil
@officedocsbot add label localization

**Comment by mypil** [comment]
@dongmicro - I would like to follow up on this. Do you have any updates?

Thank you.

**Comment by mypil** [comment]
@officedocsbot assign @dongmicro

**Comment by dongmicro** [comment]
This is MT bug, and I have confirmed the MT had this fixed and next step is contact the operation owner to re-run MT against the content to get the issue fixed. ETA is by the end of next week.

**Comment by mypil** [comment]
@officedocsbot unassign @dongmicro 
@officedocsbot assign @MollyMalone

**Comment by hyoshioka0128** [comment]
Hi, @mypil .
#145 is not Fixed.
![get-started_j2](https://user-images.githubusercontent.com/40815708/61593150-d5ef5280-ac16-11e9-9d89-041d0bad2ee7.png)

**Comment by mypil** [comment]
@MollyMalone - Can you please assist with this issue? 

Thank you.

**Comment by mypil** [comment]
@officedocsbot assign @TinaMcN

**Comment by TinaMcN** [comment]
私は人間の翻訳のためにこの記事を送った。 約2週間かかります。 (I sent this article to be human translated.  It should take approximately 2 weeks.)

**Comment by mypil** [comment]
@TinaMcN - Do you have any updates on the status of this? 

Thank you.

**Comment by TinaMcN** [comment]
記事は現在、人間が翻訳されています。 修正済みであることを確認してください。 フィードバックのおかげで再び (The article is now human translated.  Please verify that it is fixed.  Thanks again for the feedback)

**Comment by hyoshioka0128** [comment]
@TinaMcN - Corrected.
Closed #145.
Thanks.
