### ISSUE TITLE
[LOC]"___gt 設定 gt 更新 & セキュリティ gt Windows Update" needs to be replaced with "設定 > 更新とセキュリティ > Windows Update"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-insider#146]
https://docs.microsoft.com/ja-jp/windows-insider/at-home/get-started

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: ecfeb071-5a62-8103-e97b-498966b9beb3
* Version Independent ID: 88b688a6-d675-d52a-44f5-6a5ff51f5fb6
* Content: [Windows 10 Insider Preview ビルドの概要](https://docs.microsoft.com/ja-jp/windows-insider/at-home/get-started)
* Content Source: [wip/at-home/get-started.md](https://github.com/MicrosoftDocs/windows-insider/blob/master/wip/at-home/get-started.md)
* Product: **w10**
* GitHub Login: @cdmm12
* Microsoft Alias: **v-colinmit**

**Comment by mypil** [comment]
@officedocsbot assign @mypil
@officedocsbot add label localization

**Comment by mypil** [comment]
@officedocsbot assign @dongmicro

**Comment by mypil** [comment]
@dongmicro - Can you please assist with this Translation (Localization) issue?

**Comment by mypil** [comment]
@dongmicro - I would like to follow up on this. Do you have any updates?

Thank you.

**Comment by mypil** [comment]
@officedocsbot unassign @dongmicro 
@officedocsbot assign @MollyMalone

**Comment by hyoshioka0128** [comment]
Hi, @mypil .
#146 is not Fixed.
![get-started_j2](https://user-images.githubusercontent.com/40815708/61592998-e9012300-ac14-11e9-8071-51d31207e934.png)

**Comment by mypil** [comment]
@MollyMalone - Can you please assist with this issue? 

Thank you.

**Comment by mypil** [comment]
@officedocsbot assign @TinaMcN

**Comment by TinaMcN** [comment]
フィードバックをありがとうございました。 記事は機械翻訳されました。 私は人間の翻訳のためにそれを送った。 翻訳が完了するまでに最大4週間かかります。 (Thank you for the feedback.  The article was machine translated.  I sent it for human translation.  It will take up to 4 weeks to complete the translation.)

**Comment by TinaMcN** [comment]
@hyoshioka0128 記事は現在、人間が翻訳されています。 修正済みであることを確認してください。 フィードバックのおかげで再び (The article is now human translated.  Please verify that it is fixed.  Thanks again for the feedback)

**Comment by hyoshioka0128** [comment]
@TinaMcN - Corrected.
Closed #146.
Thanks.
