### ISSUE TITLE
[LOC]"[Get started] (開始する) " needs to be replaced with "「開始する」"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-insider#147]
https://docs.microsoft.com/ja-jp/windows-insider/at-home/get-started

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: ecfeb071-5a62-8103-e97b-498966b9beb3
* Version Independent ID: 88b688a6-d675-d52a-44f5-6a5ff51f5fb6
* Content: [Windows 10 Insider Preview ビルドの概要](https://docs.microsoft.com/ja-jp/windows-insider/at-home/get-started)
* Content Source: [wip/at-home/get-started.md](https://github.com/MicrosoftDocs/windows-insider/blob/master/wip/at-home/get-started.md)
* Product: **w10**
* GitHub Login: @cdmm12
* Microsoft Alias: **v-colinmit**

**Comment by mypil** [comment]
@officedocsbot assign @mypil
@officedocsbot add label localization

**Comment by mypil** [comment]
@officedocsbot assign @dongmicro

**Comment by mypil** [comment]
@dongmicro - Can you please assist with this Translation (Localization) issue?

**Comment by mypil** [comment]
@dongmicro - I would like to follow up on this. Do you have any updates?

Thank you.

**Comment by mypil** [comment]
@officedocsbot unassign @dongmicro 
@officedocsbot assign @MollyMalone

**Comment by hyoshioka0128** [comment]
Hi, @mypil .
#147 is not Fixed.
![get-started_j](https://user-images.githubusercontent.com/40815708/61592967-a4758780-ac14-11e9-8476-4dbfcbcaa37b.png)

**Comment by mypil** [comment]
@MollyMalone - Can you please assist with this issue? 

Thank you.

**Comment by mypil** [comment]
@officedocsbot assign @TinaMcN

**Comment by mypil** [comment]
@TinaMcN - Do you have any updates on the latest progress of this?

**Comment by TinaMcN** [comment]
フィードバックをありがとうございました。 記事は機械翻訳されました。 私は人間の翻訳のためにそれを送った。 翻訳が完了するまでに最大4週間かかります。 (Thank you for the feedback.  The article was machine translated.  I sent it for human translation.  It will take up to 4 weeks to complete the translation.)

**Comment by mypil** [comment]
@hyoshioka0128 - Please check and confirm if issue is fixed. Thank you.

問題が修正されたかどうかを確認してください。 ありがとうございました。

**Comment by TinaMcN** [comment]
この記事はまだ機械翻訳です。 私は、人間翻訳版がいつ準備ができているかのステータスをローカリゼーションベンダーに確認しています。 (This article is still machine translated.  I am checking with the localization vendor for status on when the human translated version will be ready.)

**Comment by mypil** [comment]
@TinaMcN - Do you have any updates on this?

Thank you.

**Comment by TinaMcN** [comment]
@hyoshioka0128 記事は現在、人間が翻訳されています。 問題が解決したことを確認してください。 フィードバックをありがとう。
(The article is now human translated.  Please verify that the issue is fixed.  Thanks again for the feedback.)

**Comment by mypil** [comment]
@hyoshioka0128 - Please check and confirm if issue is fixed. Thank you.

問題が修正されたかどうかを確認してください。 ありがとうございました。

**Comment by hyoshioka0128** [comment]
@TinaMcN @mypil - Fixed.
Closed #147
Thanks.
