### ISSUE TITLE
[LOC] Showing "![テキストの拡大](images/zooming2 .png "text zooming")" 

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-insider#150]
https://docs.microsoft.com/ja-jp/windows-insider/at-home/whats-new-wip-at-home-1809

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@officedocsbot add label localization
@officedocsbot assign @dongmicro

**Comment by mypil** [comment]
@dongmicro - Can you please assist with this Translation (Localization) issue?

**Comment by mypil** [comment]
@officedocsbot unassign @dongmicro 
@officedocsbot assign @MollyMalone

**Comment by hyoshioka0128** [comment]
Hi, @mypil .
#150 is not Fixed.
![whats-new-wip-at-home-1809_j4](https://user-images.githubusercontent.com/40815708/61592857-852a2a80-ac13-11e9-9301-c31b862af6a1.png)

**Comment by mypil** [comment]
@MollyMalone - Can you please assist with this issue? 

Thank you.

**Comment by mypil** [comment]
@officedocsbot assign @TinaMcN

**Comment by mypil** [comment]
@TinaMcN - Do you have any updates on the latest progress of this?

**Comment by TinaMcN** [comment]
フィードバックをありがとうございました。 記事は機械翻訳されました。 私は人間の翻訳のためにそれを送った。 翻訳が完了するまでに最大4週間かかります。 (Thank you for the feedback.  The article was machine translated.  I sent it for human translation.  It will take up to 4 weeks to complete the translation.)

**Comment by mypil** [comment]
@hyoshioka0128 - Please check and confirm if issue is fixed. Thank you.

問題が修正されたかどうかを確認してください。 ありがとうございました。

**Comment by TinaMcN** [comment]
この記事はまだ機械翻訳です。 私は、人間翻訳版がいつ準備ができているかのステータスをローカリゼーションベンダーに確認しています。 (This article is still machine translated.  I am checking with the localization vendor for status on when the human translated version will be ready.)

**Comment by mypil** [comment]
@TinaMcN - Do you have any updates on this?

Thank you.

**Comment by mypil** [comment]
@TinaMcN - Do you have any updates on this?

Thank you.

**Comment by TinaMcN** [comment]
@hyoshioka0128 記事は現在、人間翻訳されており、問題は修正されているようです。 修正済みであることを確認してください。 フィードバックをありがとうございました。
(The article is now human translated and the issue appears to be fixed.  Please verify that it is fixed.  Thanks again for the feedback.)

**Comment by hyoshioka0128** [comment]
@TinaMcN  - Fixed.
Closed #150
Thanks.
