### ISSUE TITLE
Showing "![text zooming](images/zooming2 .png "text zooming")" 

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-insider#151]
https://docs.microsoft.com/en-us/windows-insider/at-home/whats-new-wip-at-home-1809

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc12e690-19c5-ba46-530f-56b2e4f2bb33
* Version Independent ID: 237aec15-eb8f-78ed-086f-518b4ce554dd
* Content: [What's new in the Windows 10 Insider Preview Builds (RS5)](https://docs.microsoft.com/en-us/windows-insider/at-home/whats-new-wip-at-home-1809)
* Content Source: [wip/at-home/Whats-new-wip-at-home-1809.md](https://github.com/MicrosoftDocs/windows-insider/blob/master/wip/at-home/Whats-new-wip-at-home-1809.md)
* Product: **w10**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@officedocsbot add label localization
@officedocsbot assign @dongmicro

**Comment by mypil** [comment]
@dongmicro - Can you please assist with this Translation (Localization) issue?

**Comment by hyoshioka0128** [comment]
#151 (en-us)
![zooming2_en-us](https://user-images.githubusercontent.com/40815708/56782581-b8cb0380-6822-11e9-89be-c0c64da753fa.png)

related issue: #150 (ja-jp)
![zooming2_ja-jp](https://user-images.githubusercontent.com/40815708/56782588-bf597b00-6822-11e9-8795-f65c541c9ea0.png)

**Comment by mypil** [comment]
@officedocsbot unassign @dongmicro 
@officedocsbot assign @MollyMalone

**Comment by mypil** [comment]
@officedocsbot assign @TinaMcN

**Comment by mypil** [comment]
@TinaMcN - Do you have any updates on the latest progress of this?

**Comment by TinaMcN** [comment]
フィードバックをありがとうございました。 記事は機械翻訳されました。 私は人間の翻訳のためにそれを送った。 翻訳が完了するまでに最大4週間かかります。 (Thank you for the feedback.  The article was machine translated.  I sent it for human translation.  It will take up to 4 weeks to complete the translation.)

**Comment by mypil** [comment]
@hyoshioka0128 - Please check and confirm if issue is fixed. Thank you.

問題が修正されたかどうかを確認してください。 ありがとうございました。

**Comment by TinaMcN** [comment]
この記事はまだ機械翻訳です。 私は、人間翻訳版がいつ準備ができているかのステータスをローカリゼーションベンダーに確認しています。 (This article is still machine translated.  I am checking with the localization vendor for status on when the human translated version will be ready.)

**Comment by TinaMcN** [comment]
@hyoshioka0128 記事は現在、人間が翻訳されています。 修正済みであることを確認してください。 フィードバックのおかげで再び (The article is now human translated.  Please verify that it is fixed.  Thanks again for the feedback)

**Comment by hyoshioka0128** [comment]
@TinaMcN - Corrected.
Closed #151.
Thanks.
