### ISSUE TITLE
[LOC]Showing "![言語の設定] ページ](images/18277-image8.png "Shows the updated Language settings page")"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-insider#155]
https://docs.microsoft.com/ja-jp/windows-insider/at-home/whats-new-wip-at-home-19h1

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: b4599727-0163-9857-ce15-a2c82be9e936
* Version Independent ID: 22838d16-6ebf-280f-ed96-61a061d4b4a3
* Content: [新機能、Windows 10 Insider Preview ビルド (19 H 1)](https://docs.microsoft.com/ja-jp/windows-insider/at-home/whats-new-wip-at-home-19h1)
* Content Source: [wip/at-home/Whats-new-wip-at-home-19h1.md](https://github.com/MicrosoftDocs/windows-insider/blob/master/wip/at-home/Whats-new-wip-at-home-19h1.md)
* Product: **w10**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by mypil** [comment]
@officedocsbot assign @mypil
@officedocsbot add label localization

**Comment by mypil** [comment]
@officedocsbot assign @dongmicro

**Comment by mypil** [comment]
@dongmicro - Can you please assist with this Translation (Localization) issue?

**Comment by mypil** [comment]
@officedocsbot unassign @dongmicro 
@officedocsbot assign @MollyMalone

**Comment by hyoshioka0128** [comment]
Hi, @mypil .
Fixed.
Close #155
