### ISSUE TITLE
[LOC] "右クリック メニュー経由での Bing 検索" needs to be replaced with "右クリック メニューから Bingで検索"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-insider#156]
https://docs.microsoft.com/ja-jp/windows-insider/at-home/whats-new-wip-at-home-1809

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: dc12e690-19c5-ba46-530f-56b2e4f2bb33
* Version Independent ID: 237aec15-eb8f-78ed-086f-518b4ce554dd
* Content: [新機能、Windows 10 Insider Preview ビルド (RS5)](https://docs.microsoft.com/ja-jp/windows-insider/at-home/whats-new-wip-at-home-1809)
* Content Source: [wip/at-home/Whats-new-wip-at-home-1809.md](https://github.com/MicrosoftDocs/windows-insider/blob/master/wip/at-home/Whats-new-wip-at-home-1809.md)
* Product: **w10**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by mypil** [comment]
@officedocsbot assign @mypil
@officedocsbot add label localization

**Comment by mypil** [comment]
@officedocsbot assign @dongmicro

**Comment by mypil** [comment]
@dongmicro - Can you please assist with this Translation (Localization) issue?

**Comment by mypil** [comment]
@officedocsbot unassign @dongmicro 
@officedocsbot assign @MollyMalone

**Comment by hyoshioka0128** [comment]
Hi, @mypil .
Fixed.
Close #156
