### ISSUE TITLE
[LOC] "Settings> 更新 & Security> Windows Insider Program" needs to be replaced with "設定 > 更新とセキュリティ > Windows Insider Program"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-insider#158]
https://docs.microsoft.com/ja-jp/windows-insider/at-work-pro/wip-4-biz-register

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: e4b123d9-739d-729e-378c-b2eeb88ad8f0
* Version Independent ID: cfe614e9-a2f7-aa3e-e075-afecad232df6
* Content: [Windows 10 Insider Program for Business の登録](https://docs.microsoft.com/ja-jp/windows-insider/at-work-pro/wip-4-biz-register)
* Content Source: [wip/at-work-pro/wip-4-biz-register.md](https://github.com/MicrosoftDocs/windows-insider/blob/master/wip/at-work-pro/wip-4-biz-register.md)
* Product: **w10**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by mypil** [comment]
@officedocsbot assign @mypil
@officedocsbot add label localization

**Comment by mypil** [comment]
@officedocsbot assign @dongmicro

**Comment by mypil** [comment]
@dongmicro - Can you please assist with this Translation (Localization) issue?

**Comment by mypil** [comment]
@officedocsbot unassign @dongmicro 
@officedocsbot assign @MollyMalone

**Comment by hyoshioka0128** [comment]
Hi, @mypil .
#158 is not Fixed.
![wip-4-biz-register_j1](https://user-images.githubusercontent.com/40815708/61592709-e0f3b400-ac11-11e9-9f53-3becbf3c5a10.png)

**Comment by mypil** [comment]
@MollyMalone - Can you please assist with this issue? 

Thank you.

**Comment by mypil** [comment]
@officedocsbot assign @TinaMcN

**Comment by TinaMcN** [comment]
私は人間の翻訳のためにこの記事を送った。 約2週間かかります。 (I sent this article to be human translated.  It should take approximately 2 weeks.)

**Comment by mypil** [comment]
@TinaMcN - Do you have any updates on the status of this? 

Thank you.

**Comment by TinaMcN** [comment]
@hyoshioka0128 記事は現在、人間が翻訳されています。 修正済みであることを確認してください。 フィードバックのおかげで再び (The article is now human translated.  Please verify that it is fixed.  Thanks again for the feedback)

**Comment by mypil** [comment]
@hyoshioka0128 - Kindly check and validate if issue has been resolved. Thank you.

**Comment by hyoshioka0128** [comment]
@TinaMcN @mypil - Corrected.
Closed #158.
Thanks.
