### ISSUE TITLE
[LOC] "___gt 設定 _gt 更新 & セキュリティ _gt Windows Update を開始__" needs to be replaced with "設定 > 更新とセキュリティ > Windows Insider Program"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-insider#160]
https://docs.microsoft.com/ja-jp/windows-insider/at-work-pro/wip-4-biz-install

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 2b002f70-ea79-fc71-0b04-3d8366cbd89c
* Version Independent ID: 6f00b61f-5249-10ca-6e8f-3b250cd13a9c
* Content: [Windows 10 のプレビュー ビルドのインストールします。](https://docs.microsoft.com/ja-jp/windows-insider/at-work-pro/wip-4-biz-install)
* Content Source: [wip/at-work-pro/wip-4-biz-install.md](https://github.com/MicrosoftDocs/windows-insider/blob/master/wip/at-work-pro/wip-4-biz-install.md)
* Product: **w10**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by mypil** [comment]
@officedocsbot assign @mypil
@officedocsbot add label localization

**Comment by mypil** [comment]
@officedocsbot assign @dongmicro

**Comment by mypil** [comment]
@dongmicro - Can you please assist with this Translation (Localization) issue?

**Comment by mypil** [comment]
@officedocsbot unassign @dongmicro 
@officedocsbot assign @MollyMalone

**Comment by hyoshioka0128** [comment]
Hi, @mypil .
#160 is not Fixed.
![wip-4-biz-install_j2](https://user-images.githubusercontent.com/40815708/61592605-64aca100-ac10-11e9-9053-c9d32579c83e.png)

add:
![wip-4-biz-install_j1](https://user-images.githubusercontent.com/40815708/61592606-68d8be80-ac10-11e9-8a87-b33a95fb25aa.png)

**Comment by mypil** [comment]
@MollyMalone - Can you please assist with this issue? 

Thank you.

**Comment by mypil** [comment]
@officedocsbot assign @TinaMcN

**Comment by TinaMcN** [comment]
私は人間の翻訳のためにこの記事を送った。 約2週間かかります。 (I sent this article to be human translated.  It should take approximately 2 weeks.)

**Comment by mypil** [comment]
@TinaMcN - Do you have any updates on the status of this? 

Thank you.

**Comment by TinaMcN** [comment]
@hyoshioka0128 記事は現在、人間が翻訳されています。 修正済みであることを確認してください。 フィードバックのおかげで再び (The article is now human translated.  Please verify that it is fixed.  Thanks again for the feedback)

**Comment by mypil** [comment]
@hyoshioka0128 - Kindly check and validate if issue has been resolved. Thank you.

**Comment by mypil** [comment]
@hyoshioka0128 - Kindly check and validate if issue has been resolved. Thank you.

**Comment by hyoshioka0128** [comment]
@TinaMcN - Fixed.
Closed #160.
Thanks.
