### ISSUE TITLE
[LOC] "アプリ & 機能" needs to be replaced with "アプリと機能"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-insider#161]
https://docs.microsoft.com/ja-jp/windows-insider/at-work-pro/wip-4-biz-whats-new

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 889fc0db-6485-8268-c65e-ad4f8e69217b
* Version Independent ID: 1f76fa09-c24a-0226-034d-2a4ba4f75782
* Content: [Windows Server 10 Insider Program for Business のプレビュー ビルドの新機能](https://docs.microsoft.com/ja-jp/windows-insider/at-work-pro/wip-4-biz-whats-new)
* Content Source: [wip/at-work-pro/wip-4-biz-whats-new.md](https://github.com/MicrosoftDocs/windows-insider/blob/master/wip/at-work-pro/wip-4-biz-whats-new.md)
* Product: **w10**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by mypil** [comment]
@officedocsbot assign @mypil
@officedocsbot assign @dongmicro
@officedocsbot add label localization

**Comment by mypil** [comment]
@dongmicro - Can you please assist with this Translation (Localization) issue?

**Comment by mypil** [comment]
@officedocsbot unassign @dongmicro 
@officedocsbot assign @MollyMalone

**Comment by hyoshioka0128** [comment]
Hi, @mypil .
#161 is not Fixed.
![wip-4-biz-whats-new_j4](https://user-images.githubusercontent.com/40815708/61592510-45f9da80-ac0f-11e9-8394-0e92da080d5c.png)

**Comment by mypil** [comment]
@MollyMalone - Can you please assist with this issue? 

Thank you.

**Comment by mypil** [comment]
@officedocsbot assign @TinaMcN

**Comment by TinaMcN** [comment]
@hyoshioka0128 記事は現在、人間が翻訳されています。 修正済みであることを確認してください。 フィードバックのおかげで再び (The article is now human translated.  Please verify that it is fixed.  Thanks again for the feedback)

**Comment by hyoshioka0128** [comment]
@TinaMcN - Corrected.
Closed #161.
Thanks.
