### ISSUE TITLE
Next feature update for Windows 10 (19H1)

### ISSUE THREAD

**Issue by BR77BE** [MicrosoftDocs/windows-insider#164]
"You can get builds of 19H1 today if your device is in the Fast ring."

Not true. Do you mean Slow?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa80910a-e655-34df-d26a-b094dd8702bb
* Version Independent ID: 83b90d10-f455-fee5-cf94-2698f1ac33d6
* Content: [Flight Hub](https://docs.microsoft.com/en-us/windows-insider/flight-hub/)
* Content Source: [wip/flight-hub/index.md](https://github.com/MicrosoftDocs/windows-insider/blob/master/wip/flight-hub/index.md)
* Product: **w10**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@BR77BE - Thank you for submitting feedback.

I will get this issue over to the Windows Insider writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
Hello @BR77BE , Thank you for your feedback. You wanted to say that if the device is in Slow Ring then you will be able to get 19H1 build?

**Comment by BR77BE** [comment]
Yes, I wanted you to correct the page so that it says that, because it's currently wrong where it says, "You can get builds of 19H1 today if your device is in the **Fast** ring."; you can't, as it conflicts with, "You can get builds of **20H1** today if you've opted in to Fast builds."

**Comment by joinimran** [comment]
@BR77BE Thank you for your feedback here. I have forwarded the correction to the concerned team and it will be applied and available to the public soon.

Thanks.

**Comment by mypil** [comment]
@BR77BE - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
