### ISSUE TITLE
[LOC] "同期電話アプリ" needs to be replaced with "スマホ同期アプリ"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-insider#167]
https://docs.microsoft.com/ja-jp/windows-insider/at-home/whats-new-wip-at-home-1809

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: dc12e690-19c5-ba46-530f-56b2e4f2bb33
* Version Independent ID: 237aec15-eb8f-78ed-086f-518b4ce554dd
* Content: [新機能、Windows 10 Insider Preview ビルド (RS5)](https://docs.microsoft.com/ja-jp/windows-insider/at-home/whats-new-wip-at-home-1809)
* Content Source: [wip/at-home/Whats-new-wip-at-home-1809.md](https://github.com/MicrosoftDocs/windows-insider/blob/master/wip/at-home/Whats-new-wip-at-home-1809.md)
* Product: **w10**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by mypil** [comment]
@officedocsbot assign @mypil
@officedocsbot assign @dongmicro
@officedocsbot add label localization

**Comment by mypil** [comment]
@dongmicro - Can you please assist with this Translation (Localization) issue?

**Comment by mypil** [comment]
@officedocsbot unassign @dongmicro 
@officedocsbot assign @MollyMalone

**Comment by hyoshioka0128** [comment]
Hi, @mypil .
#167 is not Fixed.
ja-jp:https://docs.microsoft.com/ja-jp/windows-insider/at-home/whats-new-wip-at-home-1809
![whats-new-wip-at-home-1809_j3](https://user-images.githubusercontent.com/40815708/61592447-5067a480-ac0e-11e9-9c9c-4d2e19cb4145.png)

en-us:https://docs.microsoft.com/en-us/windows-insider/at-home/whats-new-wip-at-home-1809
![whats-new-wip-at-home-1809_e3](https://user-images.githubusercontent.com/40815708/61592453-59587600-ac0e-11e9-8b9e-e3ebe3c6ff4f.png)

**Comment by mypil** [comment]
@MollyMalone - Can you please assist with this issue? 

Thank you.

**Comment by mypil** [comment]
@officedocsbot assign @TinaMcN

**Comment by mypil** [comment]
@TinaMcN - Do you have any updates on the latest progress of this?

**Comment by TinaMcN** [comment]
フィードバックをありがとうございました。 記事は機械翻訳されました。 私は人間の翻訳のためにそれを送った。 翻訳が完了するまでに最大4週間かかります。 (Thank you for the feedback.  The article was machine translated.  I sent it for human translation.  It will take up to 4 weeks to complete the translation.)

**Comment by mypil** [comment]
@hyoshioka0128 - Please check and confirm if issue is fixed. Thank you.

問題が修正されたかどうかを確認してください。 ありがとうございました。

**Comment by TinaMcN** [comment]
この記事はまだ機械翻訳です。 私は、人間翻訳版がいつ準備ができているかのステータスをローカリゼーションベンダーに確認しています。 (This article is still machine translated.  I am checking with the localization vendor for status on when the human translated version will be ready.)

**Comment by mypil** [comment]
@TinaMcN - Do you have any updates on this?

Thank you.

**Comment by TinaMcN** [comment]
@hyoshioka0128 記事は現在、人間翻訳されており、問題は修正されているようです。 修正済みであることを確認してください。 フィードバックをありがとうございました。
(The article is now human translated and the issue appears to be fixed.  Please verify that it is fixed.  Thanks again for the feedback.)

**Comment by hyoshioka0128** [comment]
@TinaMcN  - Fixed.
Closed #167
Thanks.
