### ISSUE TITLE
[LOC] "同期電話アプリ" needs to be replaced with "スマホ同期アプリ"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-insider#168]
https://docs.microsoft.com/ja-jp/windows-insider/at-home/whats-new-apps-19h1

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: be459bcb-4f00-035e-758b-f96e6196e7f3
* Version Independent ID: ac56f8ae-3436-3737-0fff-7030ad2bb0e5
* Content: [Windows 10 Insider Preview ビルド (19 H 1) の新規および更新されたアプリ](https://docs.microsoft.com/ja-jp/windows-insider/at-home/whats-new-apps-19h1)
* Content Source: [wip/at-home/whats-new-apps-19h1.md](https://github.com/MicrosoftDocs/windows-insider/blob/master/wip/at-home/whats-new-apps-19h1.md)
* Product: **w10**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by mypil** [comment]
@officedocsbot assign @mypil
@officedocsbot assign @dongmicro
@officedocsbot add label localization

**Comment by mypil** [comment]
@officedocsbot unassign @dongmicro 
@officedocsbot assign @MollyMalone

**Comment by hyoshioka0128** [comment]
Hi, @mypil .
#168 is not Fixed.
ja-jp:https://docs.microsoft.com/ja-jp/windows-insider/at-home/whats-new-apps-19h1
![whats-new-apps_j](https://user-images.githubusercontent.com/40815708/61592264-0da4cd00-ac0c-11e9-9a14-beeadce27468.png)

en-us:https://docs.microsoft.com/en-us/windows-insider/at-home/whats-new-apps-19h1
![whats-new-apps_e1](https://user-images.githubusercontent.com/40815708/61592272-1bf2e900-ac0c-11e9-9470-9d3ae02f4ba8.png)
![whats-new-apps_e2](https://user-images.githubusercontent.com/40815708/61592274-21503380-ac0c-11e9-8185-6cb7aa678228.png)

**Comment by mypil** [comment]
@MollyMalone - Can you please assist with this issue? 

Thank you.

**Comment by mypil** [comment]
@officedocsbot assign @TinaMcN

**Comment by mypil** [comment]
@TinaMcN - Do you have any updates on the latest progress of this?

**Comment by TinaMcN** [comment]
フィードバックをありがとうございました。 記事は機械翻訳されました。 私は人間の翻訳のためにそれを送った。 翻訳が完了するまでに最大4週間かかります。 (Thank you for the feedback.  The article was machine translated.  I sent it for human translation.  It will take up to 4 weeks to complete the translation.)

**Comment by mypil** [comment]
@hyoshioka0128 - Please check and confirm if issue is fixed. Thank you.

問題が修正されたかどうかを確認してください。 ありがとうございました。

**Comment by TinaMcN** [comment]
この記事はまだ機械翻訳です。 私は、人間翻訳版がいつ準備ができているかのステータスをローカリゼーションベンダーに確認しています。 (This article is still machine translated.  I am checking with the localization vendor for status on when the human translated version will be ready.)

**Comment by mypil** [comment]
@TinaMcN - Do you have any updates on this?

Thank you.

**Comment by TinaMcN** [comment]
@hyoshioka0128 この問題が修正されたかどうかを確認してください。 英語 + 日本語のページが更新されました。 (Can you please check if this issue has been fixed.  The English + Japanese pages have been updated.)

**Comment by hyoshioka0128** [comment]
@TinaMcN - Not Corrected.
"同期電話" needs to be replaced with "スマホ同期アプリ"
![YourPhone](https://user-images.githubusercontent.com/40815708/68578794-11f43f00-04b6-11ea-9545-91208e490543.png)

Thanks.

**Comment by TinaMcN** [comment]
@hyoshioka0128 お詫び申し上げます。  私は再び人間の翻訳されるように記事を送った。 (I apologise for this.   I sent the article to be human translated again.  )

**Comment by hyoshioka0128** [comment]
same page
 ja-jp:
![whats-new-apps_j3](https://user-images.githubusercontent.com/40815708/68993858-d98e9f80-08bf-11ea-8a07-4a3378d8b4e7.png)

 en-us:
![whats-new-apps_e3](https://user-images.githubusercontent.com/40815708/68993864-e3b09e00-08bf-11ea-9129-f2e411488969.png)

**Comment by mypil** [comment]
@TinaMcN - Do you have any updates on the status of this? 

Thank you.

**Comment by TinaMcN** [comment]
@hyoshioka0128 記事は現在、人間が翻訳されています。 修正済みであることを確認してください。 フィードバックのおかげで再び (The article is now human translated.  Please verify that it is fixed.  Thanks again for the feedback)

**Comment by mypil** [comment]
@hyoshioka0128 - Kindly check and validate if issue has been resolved. Thank you.

**Comment by hyoshioka0128** [comment]
@TinaMcN @mypil - Corrected.
Closed #168.
Thanks.
