### ISSUE TITLE
[LOC] "ウイルス & Threat Protection" needs to be replaced with "ウイルスと脅威の防止"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-insider#172]
https://docs.microsoft.com/ja-jp/windows-insider/at-home/whats-new-wip-at-home-19h1

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: b4599727-0163-9857-ce15-a2c82be9e936
* Version Independent ID: 22838d16-6ebf-280f-ed96-61a061d4b4a3
* Content: [新機能、Windows 10 Insider Preview ビルド (19 H 1)](https://docs.microsoft.com/ja-jp/windows-insider/at-home/whats-new-wip-at-home-19h1)
* Content Source: [wip/at-home/Whats-new-wip-at-home-19h1.md](https://github.com/MicrosoftDocs/windows-insider/blob/master/wip/at-home/Whats-new-wip-at-home-19h1.md)
* Product: **w10**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by mypil** [comment]
@officedocsbot assign @mypil
@officedocsbot assign @dongmicro
@officedocsbot add label localization

**Comment by mypil** [comment]
@hyoshioka0128 - please see update [here](https://github.com/MicrosoftDocs/windows-insider/issues/123#issuecomment-490486066).

**Comment by mypil** [comment]
@officedocsbot unassign @dongmicro 
@officedocsbot assign @MollyMalone

**Comment by hyoshioka0128** [comment]
Hi, @mypil .
#172 is not Fixed.
![whats-new-wip-at-home-19h1_j](https://user-images.githubusercontent.com/40815708/61592092-57d87f00-ac09-11e9-987a-66b442cfc894.png)

**Comment by mypil** [comment]
@MollyMalone - Can you please assist with this issue? 

Thank you.

**Comment by mypil** [comment]
@officedocsbot assign @TinaMcN

**Comment by TinaMcN** [comment]
@hyoshioka0128 記事は現在、人間が翻訳されています。 修正済みであることを確認してください。 フィードバックのおかげで再び (The article is now human translated.  Please verify that it is fixed.  Thanks again for the feedback)

**Comment by hyoshioka0128** [comment]
@TinaMcN - Corrected.
Closed #172.
Thanks.
