### ISSUE TITLE
[LOC] "ウイルス & Threat Protection" needs to be replaced with "ウイルスと脅威の防止"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-insider#174]
https://docs.microsoft.com/ja-jp/windows-insider/at-work-pro/wip-4-biz-whats-new

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 889fc0db-6485-8268-c65e-ad4f8e69217b
* Version Independent ID: 1f76fa09-c24a-0226-034d-2a4ba4f75782
* Content: [Windows Server 10 Insider Program for Business のプレビュー ビルドの新機能](https://docs.microsoft.com/ja-jp/windows-insider/at-work-pro/wip-4-biz-whats-new)
* Content Source: [wip/at-work-pro/wip-4-biz-whats-new.md](https://github.com/MicrosoftDocs/windows-insider/blob/master/wip/at-work-pro/wip-4-biz-whats-new.md)
* Product: **w10**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by mypil** [comment]
@officedocsbot assign @mypil
@officedocsbot assign @dongmicro
@officedocsbot add label localization

**Comment by mypil** [comment]
@hyoshioka0128 - please see update [here](https://github.com/MicrosoftDocs/windows-insider/issues/123#issuecomment-490486066).

**Comment by mypil** [comment]
@officedocsbot unassign @dongmicro 
@officedocsbot assign @MollyMalone

**Comment by hyoshioka0128** [comment]
Hi, @mypil .
#174 is not Fixed.
![wip-4-biz-whats-new_j2](https://user-images.githubusercontent.com/40815708/61592020-6bcfb100-ac08-11e9-8484-ac79d4805cab.png)

**Comment by mypil** [comment]
@MollyMalone - Can you please assist with this issue? 

Thank you.

**Comment by mypil** [comment]
@officedocsbot assign @TinaMcN

**Comment by TinaMcN** [comment]
@hyoshioka0128 記事は現在、人間が翻訳されています。 修正済みであることを確認してください。 フィードバックをありがとう。(The article is now human translated.  Please verify that it is fixed.  Thanks again for the feedback.)

**Comment by hyoshioka0128** [comment]
@TinaMcN - Content disappeared
Closed #174.
Thanks.
