### ISSUE TITLE
[LOC]Back-Translation "__hkey_local_machine \"→"HKEY_LOCAL_MACHINE\～"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-insider#175]
"__hkey_local_machine \software\policies\microsoft\windows\windowsupdate__"
 ↓
"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate"

https://docs.microsoft.com/ja-jp/windows-insider/at-work-pro/wip-4-biz-manage

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 70755f6c-a8f2-ca3b-e9cc-1966c1fac459
* Version Independent ID: 53f2d3f5-eabe-5f47-265b-a2077f6d842d
* Content: [Windows Insider Preview ビルドの管理](https://docs.microsoft.com/ja-jp/windows-insider/at-work-pro/wip-4-biz-manage)
* Content Source: [wip/at-work-pro/wip-4-biz-manage.md](https://github.com/MicrosoftDocs/windows-insider/blob/master/wip/at-work-pro/wip-4-biz-manage.md)
* Product: **w10**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@officedocsbot assign @dongmicro
@officedocsbot add label localization

**Comment by mypil** [comment]
@hyoshioka0128 - please see update [here](https://github.com/MicrosoftDocs/windows-insider/issues/123#issuecomment-490486066).

**Comment by mypil** [comment]
@officedocsbot unassign @dongmicro 
@officedocsbot assign @MollyMalone

**Comment by hyoshioka0128** [comment]
Hi, @mypil .
#175 is not Fixed.
ja-jp:https://docs.microsoft.com/ja-jp/windows-insider/at-work-pro/wip-4-biz-manage
![wip-4-biz-manage_j2](https://user-images.githubusercontent.com/40815708/61588496-ab31d980-abd7-11e9-8068-08d04ac75499.png)

en-us:https://docs.microsoft.com/en-us/windows-insider/at-work-pro/wip-4-biz-manage
![Uploading wip-4-biz-manage_e2.png…]()

**Comment by mypil** [comment]
@MollyMalone - Can you please assist with this issue? 

Thank you.

**Comment by mypil** [comment]
@officedocsbot assign @TinaMcN

**Comment by mypil** [comment]
@TinaMcN - Do you have any updates on the latest progress of this?

**Comment by TinaMcN** [comment]
フィードバックをありがとうございました。 記事は機械翻訳されました。 私は人間の翻訳のためにそれを送った。 翻訳が完了するまでに最大4週間かかります。 (Thank you for the feedback.  The article was machine translated.  I sent it for human translation.  It will take up to 4 weeks to complete the translation.)

**Comment by mypil** [comment]
@hyoshioka0128 - Please check and confirm if issue is fixed. Thank you.

問題が修正されたかどうかを確認してください。 ありがとうございました。

**Comment by TinaMcN** [comment]
この記事はまだ機械翻訳です。 私は、人間翻訳版がいつ準備ができているかのステータスをローカリゼーションベンダーに確認しています。 (This article is still machine translated.  I am checking with the localization vendor for status on when the human translated version will be ready.)

**Comment by mypil** [comment]
@TinaMcN - Do you have any updates on this?

Thank you.

**Comment by TinaMcN** [comment]
記事は現在、人間が翻訳されています。 問題が解決したことを確認してください。 フィードバックをありがとう。
(The article is now human translated.  Please verify that the issue is fixed.  Thanks again for the feedback.)

**Comment by hyoshioka0128** [comment]
@TinaMcN - Not corrected.
"__HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate__" is showing(Same as 21 Jul ).
Thanks.

**Comment by TinaMcN** [comment]
吉大さん、ありがとうございました。 私はそれを人間の翻訳に送り返した。

**Comment by TinaMcN** [comment]
記事は現在、人間が翻訳されています。 修正済みであることを確認してください。 フィードバックをありがとう。(The article is now human translated.  Please verify that it is fixed.  Thanks again for the feedback.)

**Comment by hyoshioka0128** [comment]
@TinaMcN - Corrected.
Closed #175.
Thanks.
