### ISSUE TITLE
[LOC]fixed inappropriate japanese "Settings"→"設定"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-insider#176]
"__Security>Windows 更新 Settings>Update &__"
 ↓
"設定 > 更新とセキュリティ > Windows Update"

https://docs.microsoft.com/ja-jp/windows-insider/at-work-pro/wip-4-biz-manage

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 70755f6c-a8f2-ca3b-e9cc-1966c1fac459
* Version Independent ID: 53f2d3f5-eabe-5f47-265b-a2077f6d842d
* Content: [Windows Insider Preview ビルドの管理](https://docs.microsoft.com/ja-jp/windows-insider/at-work-pro/wip-4-biz-manage)
* Content Source: [wip/at-work-pro/wip-4-biz-manage.md](https://github.com/MicrosoftDocs/windows-insider/blob/master/wip/at-work-pro/wip-4-biz-manage.md)
* Product: **w10**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@officedocsbot assign @dongmicro
@officedocsbot add label localization

**Comment by mypil** [comment]
@hyoshioka0128 - please see update [here](https://github.com/MicrosoftDocs/windows-insider/issues/123#issuecomment-490486066).

**Comment by mypil** [comment]
@officedocsbot unassign @dongmicro 
@officedocsbot assign @MollyMalone

**Comment by hyoshioka0128** [comment]
Hi, @mypil .
#176 is not Fixed.
![wip-4-biz-manage_j](https://user-images.githubusercontent.com/40815708/61588394-b257e800-abd5-11e9-864b-7a74699be16a.png)

**Comment by mypil** [comment]
@MollyMalone - Can you please assist with this issue? 

Thank you.

**Comment by mypil** [comment]
@officedocsbot assign @TinaMcN

**Comment by mypil** [comment]
@TinaMcN - Do you have any updates on the latest progress of this?

**Comment by TinaMcN** [comment]
フィードバックをありがとうございました。 記事は機械翻訳されました。 私は人間の翻訳のためにそれを送った。 翻訳が完了するまでに最大4週間かかります。 (Thank you for the feedback.  The article was machine translated.  I sent it for human translation.  It will take up to 4 weeks to complete the translation.)

**Comment by mypil** [comment]
@hyoshioka0128 - Please check and confirm if issue is fixed. Thank you.

問題が修正されたかどうかを確認してください。 ありがとうございました。

**Comment by TinaMcN** [comment]
この記事はまだ機械翻訳です。 私は、人間翻訳版がいつ準備ができているかのステータスをローカリゼーションベンダーに確認しています。 (This article is still machine translated.  I am checking with the localization vendor for status on when the human translated version will be ready.)

**Comment by mypil** [comment]
@TinaMcN - Do you have any updates on this?

Thank you.

**Comment by TinaMcN** [comment]
@hyoshioka0128 記事は現在、人間が翻訳されています。 修正済みであることを確認してください。 フィードバックのおかげで再び (The article is now human translated.  Please verify that it is fixed.  Thanks again for the feedback)

**Comment by hyoshioka0128** [comment]
@TinaMcN - Corrected.
Closed #176.
Thanks.
