### ISSUE TITLE
Android phone’s notifications

### ISSUE THREAD

**Issue by GusDS** [MicrosoftDocs/windows-insider#178]
I was receiving Android phone’s notifications on my PC last year with Android 6.0 without problems until it was apparently discontinued. Now it's announced on Windows Insider as a future feature only for Android 7.0+. Why?

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@GusDS - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows Insider Program:  **https://techcommunity.microsoft.com/t5/Windows-Insider-Program/bd-p/WindowsInsiderProgram**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot close
