### ISSUE TITLE
"new app update to Skip Ahead" needs to be replaced with "new app update to Snip & Sketch"

### ISSUE THREAD

**Issue by emmett421** [MicrosoftDocs/windows-insider#181]
I assume that "Skip Ahead" was meant to be "Snip & Sketch". If not, it should be clarified what that means.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be459bcb-4f00-035e-758b-f96e6196e7f3
* Version Independent ID: ac56f8ae-3436-3737-0fff-7030ad2bb0e5
* Content: [New and updated apps in the Windows 10 Insider Preview Builds (19H1)](https://docs.microsoft.com/en-us/windows-insider/at-home/whats-new-apps-19h1#feedback)
* Content Source: [wip/at-home/whats-new-apps-19h1.md](https://github.com/MicrosoftDocs/windows-insider/blob/master/wip/at-home/whats-new-apps-19h1.md)
* Product: **w10**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@emmett421 - Thank you for submitting feedback.

I will get this issue over to the Windows Insider writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@emmett421  Thank you for your feedback. We have made the changes via PR https://github.com/MicrosoftDocs/windows-insider/pull/182

**Comment by mypil** [comment]
@emmett421 - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
