### ISSUE TITLE
cant activate win 10 enterprise

### ISSUE THREAD

**Issue by ontomorlight03** [MicrosoftDocs/windows-insider#183]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa80910a-e655-34df-d26a-b094dd8702bb
* Version Independent ID: 83b90d10-f455-fee5-cf94-2698f1ac33d6
* Content: [Flight Hub](https://docs.microsoft.com/en-us/windows-insider/flight-hub/)
* Content Source: [wip/flight-hub/index.md](https://github.com/MicrosoftDocs/windows-insider/blob/master/wip/flight-hub/index.md)
* Product: **w10**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by mypil** [comment]
@ontomorlight03 - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows Insider Program: **https://techcommunity.microsoft.com/t5/Windows-Insider-Program/bd-p/WindowsInsiderProgram**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@officedocsbot close
