### ISSUE TITLE
[LOC] "更新 & セキュリティ" needs to be replaced with "更新とセキュリティ"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-insider#189]
related issue: #123 

https://docs.microsoft.com/ja-jp/windows-insider/at-work-pro/wip-4-biz-whats-new

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 889fc0db-6485-8268-c65e-ad4f8e69217b
* Version Independent ID: 1f76fa09-c24a-0226-034d-2a4ba4f75782
* Content: [Windows Server 10 Insider Program for Business のプレビュー ビルドの新機能](https://docs.microsoft.com/ja-jp/windows-insider/at-work-pro/wip-4-biz-whats-new)
* Content Source: [wip/at-work-pro/wip-4-biz-whats-new.md](https://github.com/MicrosoftDocs/windows-insider/blob/master/wip/at-work-pro/wip-4-biz-whats-new.md)
* Product: **w10**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by mypil** [comment]
@officedocsbot assign @mypil
@officedocsbot assign @dongmicro
@officedocsbot add label localization

**Comment by mypil** [comment]
@dongmicro - Kindly assist with this additional translation/localization issue. Thank you.

**Comment by mypil** [comment]
@officedocsbot unassign @dongmicro 
@officedocsbot assign @MollyMalone

**Comment by hyoshioka0128** [comment]
Hello, @mypil 
#189 is not Fixd.

ja-jp:https://docs.microsoft.com/ja-jp/windows-insider/at-work-pro/wip-4-biz-whats-new
![wip-4-biz-whats-new_j](https://user-images.githubusercontent.com/40815708/61588325-ae779600-abd4-11e9-9645-e2693f02e31c.png)

en-us:https://docs.microsoft.com/en-us/windows-insider/at-work-pro/wip-4-biz-whats-new
![wip-4-biz-whats-new_e](https://user-images.githubusercontent.com/40815708/61588323-a881b500-abd4-11e9-91b8-33b014c06763.png)

**Comment by mypil** [comment]
@MollyMalone - Can you please assist with this unresolved issue? 

Thank you.

**Comment by mypil** [comment]
@officedocsbot assign @TinaMcN

**Comment by TinaMcN** [comment]
@hyoshioka0128 フィードバックをありがとうございました。 これは MT ツールの問題です。 私はツールの所有者に問題を報告しました。 この問題がすぐに解決されるとは思いません。 修正が必要になったときに更新します。(Thank you for the feedback. This is a problem with the MT tool. I have reported the problem to the tool owners. I don't expect this issue to be fixed quickly. I will update when we have a fix.)

**Comment by TinaMcN** [comment]
@hyoshioka0128 記事は現在、人間が翻訳されています。 修正済みであることを確認してください。 フィードバックのおかげで再び (The article is now human translated.  Please verify that it is fixed.  Thanks again for the feedback)

**Comment by hyoshioka0128** [comment]
@TinaMcN - Corrected.
Closed #189.
Thanks.
