### ISSUE TITLE
Faster sign-in

### ISSUE THREAD

**Issue by Atamido** [MicrosoftDocs/windows-insider#20]
The Faster sign-in section describes how to enable it, but doesn't indicate what is being given up.  Are there applications or features that will not work for fast signed in users?  Will some stuff simply work more slowly opening for the first time?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 889fc0db-6485-8268-c65e-ad4f8e69217b
* Version Independent ID: 1f76fa09-c24a-0226-034d-2a4ba4f75782
* Content: [What's new in the Windows Server 10 Insider Program for Business Preview Builds](https://docs.microsoft.com/en-us/windows-insider/at-work-pro/wip-4-biz-whats-new#faster-sign-in-to-a-windows-10-shared-pc-build-17713)
* Content Source: [wip/at-work-pro/wip-4-biz-whats-new.md](https://github.com/MicrosoftDocs/windows-insider/blob/master/wip/at-work-pro/wip-4-biz-whats-new.md)
* Service: **wip-at-work-pro**
* GitHub Login: @dawn.wood
* Microsoft Alias: **dawn.wood**

**Comment by dawnwood** [comment]
Hi @Atamido, thank you for the question.
When the FastSignIn feature is enabled, Windows creates a “candidate profile” in advance. Once the user has successfully authenticated during the sign-in process, the account is connected to the pre-created candidate profile, which results in a time savings.

No noticeable difference in end-user experience is expected. We encourage you to try out the feature and provide any feedback you might have.

**Comment by Atamido** [comment]
As there is "no noticeable difference in end-user experience", is there any reason this feature is not enabled by default?  Or is the feature intended to be broadly tested first?

**Comment by dawnwood** [comment]
FastFirstSignIn has been designed for Shared PCs where transient users come and go. Such users are the ones who will benefit the most as their experience is tremendously improved. As mentioned, in order for this to work, the System creates a candidate profile which uses up resources. 

On personal PC’s this feature will not be used, which is why it is not enabled by default.
