### ISSUE TITLE
日本語版での情報不足

### ISSUE THREAD

**Issue by 16dyui** [MicrosoftDocs/windows-insider#208]
日本語翻訳ページが英語版に追従していません。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: fa80910a-e655-34df-d26a-b094dd8702bb
* Version Independent ID: 83b90d10-f455-fee5-cf94-2698f1ac33d6
* Content: [フライト ハブ](https://docs.microsoft.com/ja-jp/windows-insider/flight-hub/#next-feature-update-for-windows-10-19h2)
* Content Source: [wip/flight-hub/index.md](https://github.com/MicrosoftDocs/windows-insider/blob/master/wip/flight-hub/index.md)
* Product: **w10**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by mypil** [comment]
@officedocsbot assign @mypil
@officedocsbot assign @dongmicro
@officedocsbot add label localization

**Comment by mypil** [comment]
@dongmicro - Kindly assist with this new translation/localization issue.

 Thank you.

**Comment by mypil** [comment]
@officedocsbot unassign @dongmicro 
@officedocsbot assign @MollyMalone

**Comment by mypil** [comment]
@16dyui - Can you please validate and confirm if this Translation (Localization) issue that you opened has been resolved? 

The latest update we received is that the repos were just migrated so this may have already fixed the MT issues.  Thank you!

**Comment by 16dyui** [comment]
Thunk you.
I have confirmed.
