### ISSUE TITLE
Snip & Sketch Program

### ISSUE THREAD

**Issue by rbonomo** [MicrosoftDocs/windows-insider#209]
Hey Guys,

Snip & Sketch is a cool replacement for Snipping Tool. However, your developers forgot to include the "window capture" mode that Snipping Tool has. Please put it in there.

Thanks

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@rbonomo - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback on how to make the Windows Insider Program better. They keep a close tab on user feedback and it would be awesome if you could add your voice via [Feedback Hub] (https://insider.windows.com/en-us/how-to-feedback/)
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by ItzLevvie** [comment]
@rbonomo Isn't it already on there? https://docs.microsoft.com/en-us/windows-insider/at-home/whats-new-wip-at-home-19h1#bringing-window-snip-to-your-modern-snipping-experience

**Comment by rbonomo** [comment]
I've updated to Windows build 1903 and it is there. Thanks!
