### ISSUE TITLE
TOC for windows-insider ja-jp document is not translated. 

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-insider#211]
![windows-insider_j](https://user-images.githubusercontent.com/40815708/61549365-c8a55d00-aa8a-11e9-8560-4281b07a5a5d.png)

https://docs.microsoft.com/ja-jp/windows-insider/at-home/

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@officedocsbot assign @mypil
@officedocsbot assign @MollyMalone
@officedocsbot add label localization

**Comment by mypil** [comment]
@MollyMalone - Can you please assist with this new translation/localization issue?

Thank you.

**Comment by mypil** [comment]
@officedocsbot assign @TinaMcN

**Comment by mypil** [comment]
@TinaMcN - Do you have any updates on the latest progress of this?

**Comment by TinaMcN** [comment]
@hyoshioka0128 この深刻な問題を報告していただきありがとうございます。 他の言語でも起こっています。 私はサポートチームにエスカレートしました。 (Thank you for reporting this serious issue.  It is also happening for other languages.  I have escalated to my support team.)

**Comment by mypil** [comment]
@TinaMcN - Do you have any updates on the status of this?

Thank you.

**Comment by TinaMcN** [comment]
この問題は修正されました。 目次が翻訳されました。 この問題を報告していただきありがとうございます。 (This issue is now fixed.  The Table Of Contents is now translated.  Thanks again for reporting this issue.)

**Comment by hyoshioka0128** [comment]
@TinaMcN @mypil - Fixed. Thank you.
Closed #211
