### ISSUE TITLE
[LOC] Broken link "https://aka.ms/windowscontainer"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-insider#212]
ja-jp:https://docs.microsoft.com/ja-jp/windows-insider/at-home/whats-new-wip-at-home-1809
![whats-new-wip-at-home-1809_j](https://user-images.githubusercontent.com/40815708/61573736-64b48000-aaee-11e9-9ce2-a2464dff927b.png)

en-us:https://docs.microsoft.com/en-us/windows-insider/at-home/whats-new-wip-at-home-1809
![whats-new-wip-at-home-1809_e](https://user-images.githubusercontent.com/40815708/61573735-61b98f80-aaee-11e9-8b72-1154c119c75a.png)

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@officedocsbot assign @mypil
@officedocsbot assign @MollyMalone
@officedocsbot add label localization

**Comment by mypil** [comment]
@MollyMalone - Can you please assist with this new translation/localization issue?

Thank you.

**Comment by mypil** [comment]
@officedocsbot assign @TinaMcN

**Comment by mypil** [comment]
@TinaMcN - Do you have any updates on the latest progress of this?

**Comment by TinaMcN** [comment]
フィードバックをありがとうございました。 記事は機械翻訳されました。 私は人間の翻訳のためにそれを送った。 翻訳が完了するまでに最大4週間かかります。 (Thank you for the feedback.  The article was machine translated.  I sent it for human translation.  It will take up to 4 weeks to complete the translation.)

**Comment by mypil** [comment]
@hyoshioka0128 - Please check and confirm if issue is fixed. Thank you.

問題が修正されたかどうかを確認してください。 ありがとうございました。

**Comment by TinaMcN** [comment]
この記事はまだ機械翻訳です。 私は、人間翻訳版がいつ準備ができているかのステータスをローカリゼーションベンダーに確認しています。 (This article is still machine translated.  I am checking with the localization vendor for status on when the human translated version will be ready.)

**Comment by mypil** [comment]
@TinaMcN - Do you have any updates on this?

Thank you.

**Comment by TinaMcN** [comment]
@hyoshioka0128 記事は現在、人間が翻訳されています。 問題が解決したことを確認してください。 フィードバックをありがとう。
(The article is now human translated.  Please verify that the issue is fixed.  Thanks again for the feedback.)

**Comment by hyoshioka0128** [comment]
@TinaMcN - Not corrected.
"https://aka.ms/windowscontainer" is Broken link(Same as 20 Jul).
Thanks.

**Comment by TinaMcN** [comment]
@hyoshioka0128 お詫び申し上げます。  私は再び人間の翻訳されるように記事を送った。 私は翻訳者にリンクを修正するように頼みました。(I apologise for this.   I sent the article to be human translated again.  I asked the translators to fix the link.)

**Comment by mypil** [comment]
@TinaMcN - Do you have any updates on the status of this? 

Thank you.

**Comment by TinaMcN** [comment]
@hyoshioka0128 記事は現在、人間が翻訳されています。 修正済みであることを確認してください。 フィードバックのおかげで再び (The article is now human translated.  Please verify that it is fixed.  Thanks again for the feedback)

**Comment by mypil** [comment]
@hyoshioka0128 - Kindly check and validate if issue has been resolved. Thank you.

**Comment by hyoshioka0128** [comment]
@TinaMcN  @mypil - Not corrected.

**Comment by TinaMcN** [comment]
@hyoshioka0128 そのことについてお詫び申し上げます。  私は翻訳者に問題を調査し、修正するように頼みました。 (I apologise about that.   I have asked the translators to investigate and fix the issue.)

**Comment by TinaMcN** [comment]
@mypil the localization engineers report that this seems to be a source issue.  Can you help with that?
![image](https://user-images.githubusercontent.com/53281468/71376547-b4541780-2576-11ea-8ce4-7d9d1019ac4e.png)

**Comment by mypil** [comment]
@TinaMcN - Sure, I assigned @VLG17 to help with this issue. 

@VLG17 - As discussed, please do the needful. Thank you.

**Comment by VLG17** [comment]
@TinaMcN @mypil There is no issue with the "en-us" article, as pointed out by the OP. The link works there.

The problem is with the "ja-jp" versioning, where the link does not work, because there is no space between the link and the text that comes after.

ja-jp: ![image](https://user-images.githubusercontent.com/41186174/71510408-8123c800-2897-11ea-8424-fa3e4e771320.png)

en-us: ![image](https://user-images.githubusercontent.com/41186174/71510430-939e0180-2897-11ea-969c-f490af99a63c.png)

I don't have rights to edit the "ja-jp", and also don't think i should do that.

**Comment by mypil** [comment]
@TinaMcN - Can your team help to correct the "ja-jp" version of this doc by adding a space between the link and the text that comes after? This might help fix the issue.

Thank you.

**Comment by TinaMcN** [comment]
@mypil thanks for the suggestion, that fixed the problem.  @hyoshioka0128 問題が修正されたので、あなたはそれを閉じてください (can you please close it as the issue is now fixed)

**Comment by hyoshioka0128** [comment]
@TinaMcN - Corrected.
Closed #212.
Thanks.
