### ISSUE TITLE
""いいね!" を使用した輻輳制御" needs to be replaced with ”LEDBATによる輻輳制御”

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-insider#214]
ja-jp:https://docs.microsoft.com/ja-jp/windows-insider/at-work/whats-new-wip-at-work-1809
![whats-new-wip-at-work-1809_j](https://user-images.githubusercontent.com/40815708/61680581-16e58500-ad45-11e9-8abd-1483d9367a07.png)

en-us:https://docs.microsoft.com/en-us/windows-insider/at-work/whats-new-wip-at-work-1809
![whats-new-wip-at-work-1809_e](https://user-images.githubusercontent.com/40815708/61680584-1d73fc80-ad45-11e9-9e0a-4882c78fa58b.png)

**Comment by mypil** [comment]
@officedocsbot assign @mypil
@officedocsbot assign @MollyMalone
@officedocsbot add label localization

**Comment by mypil** [comment]
@MollyMalone - Can you please assist with this new translation/localization issue?

Thank you.

**Comment by mypil** [comment]
@officedocsbot assign @TinaMcN

**Comment by mypil** [comment]
@TinaMcN - Do you have any updates on the latest progress of this?

**Comment by TinaMcN** [comment]
フィードバックをありがとうございました。 記事は機械翻訳されました。 私は人間の翻訳のためにそれを送った。 翻訳が完了するまでに最大4週間かかります。 (Thank you for the feedback.  The article was machine translated.  I sent it for human translation.  It will take up to 4 weeks to complete the translation.)

**Comment by mypil** [comment]
@hyoshioka0128 - Please check and confirm if issue is fixed. Thank you.

問題が修正されたかどうかを確認してください。 ありがとうございました。

**Comment by TinaMcN** [comment]
この記事はまだ機械翻訳です。 私は、人間翻訳版がいつ準備ができているかのステータスをローカリゼーションベンダーに確認しています。 (This article is still machine translated.  I am checking with the localization vendor for status on when the human translated version will be ready.)

**Comment by TinaMcN** [comment]
@hyoshioka0128 記事は現在、人間翻訳されており、問題は修正されているようです。 修正済みであることを確認してください。 フィードバックをありがとうございました。
(The article is now human translated and the issue appears to be fixed.  Please verify that it is fixed.  Thanks again for the feedback.)

**Comment by hyoshioka0128** [comment]
@TinaMcN  - Not corrected.
""いいね!" を使用した輻輳制御" is showing.
Thanks.

**Comment by TinaMcN** [comment]
@hyoshioka0128 ごめんなさい。 私は次の2つの記事の間で混乱しました。
https://docs.microsoft.com/ja-jp/windows-insider/at-home/Whats-new-wip-at-home-1809 (現在は人間が翻訳)
https://docs.microsoft.com/ja-jp/windows-insider/at-work/whats-new-wip-at-work-1809 (スティル マシン翻訳済み)
私は今、人間の翻訳のために何を新しいwip-at-work-1809に送っています。
準備が整うには2週間かかります。
(I am sorry.  I was confused between the following 2 articles.
https://docs.microsoft.com/ja-jp/windows-insider/at-home/Whats-new-wip-at-home-1809 (now human translated)
https://docs.microsoft.com/ja-jp/windows-insider/at-work/whats-new-wip-at-work-1809 (still machine translated)
I have now sent whats-new-wip-at-work-1809 for human translation.
It will take 2 weeks to be ready.)

**Comment by TinaMcN** [comment]
@hyoshioka0128 記事は現在、人間が翻訳されています。 問題が解決したことを確認してください。 フィードバックをありがとう。
(The article is now human translated.  Please verify that the issue is fixed.  Thanks again for the feedback.)

**Comment by hyoshioka0128** [comment]
@TinaMcN - Corrected.
Closed #214.
Thanks.
