### ISSUE TITLE
Great way to track progress!

### ISSUE THREAD

**Issue by k3tonan** [MicrosoftDocs/windows-insider#22]
Either I have overlooked this or this was recently introduced. I have been using some unofficial site for tracking that is confusing at least to start. This computes with my mind.

Thanks!

P.S. I wish every application had feedback and tracking.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa80910a-e655-34df-d26a-b094dd8702bb
* Version Independent ID: 83b90d10-f455-fee5-cf94-2698f1ac33d6
* Content: [Flight Hub](https://docs.microsoft.com/en-us/windows-insider/flight-hub/)
* Content Source: [wip/flight-hub/index.md](https://github.com/MicrosoftDocs/windows-insider/blob/master/wip/flight-hub/index.md)
* Service: **wip**
* GitHub Login: @dawn.wood
* Microsoft Alias: **dawn.wood**

**Comment by dawnwood** [comment]
Hi @k3tonan Thank you for the feedback! We're glad this page is helpful. 
Best,
Dawn
