### ISSUE TITLE
Flight Hub doc for Windows 10 Insider build Needs Updates

### ISSUE THREAD

**Issue by sujayvsarma** [MicrosoftDocs/windows-insider#237]
@lizap Please update the Flight Hub doc for Windows 10 Insider build 18995.

https://github.com/microsoftdocs/windows-insider/blob/master/wip/flight-hub/index.md

**Comment by mypil** [comment]
@sujayvsarma  - Thank you for submitting feedback.

I will get this issue over to the Windows Insider writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@bleblancMSFT - Can you please assist with this request? This might be addressed in PR #234 which was created by @ItzLevvie 

Thank you.

cc: @kenwith

**Comment by bleblancMSFT** [comment]
Hi @mypil - this was added in via PR 234. I approved the merge :-)
