### ISSUE TITLE
The Windows Insider "Working with rings and updates" need to be updated because Skip Ahead is now gone

### ISSUE THREAD

**Issue by eriawan** [MicrosoftDocs/windows-insider#256]
The page under the section of Windows Insider Program titled[ "Working with rings and updates"](https://docs.microsoft.com/windows-insider/at-home/rings) needs to be updated, because the "Skip Ahead" insider release ring is gone.

Based on this original announcement, Skip Ahead is gone:  https://blogs.windows.com/windowsexperience/2019/11/05/announcing-windows-10-insider-preview-build-19018

Please update the page.

cc @bleblancMSFT

**Comment by eriawan** [comment]
@mypil @bleblancMSFT 

Pardon, any update on this issue?

**Comment by bleblancMSFT** [comment]
We are working on updating this content.

**Comment by eriawan** [comment]
Thanks for the update, @bleblancMSFT 👍

**Comment by mypil** [comment]
@eriawan - From our understanding, the issue has been answered by bleblancMSFT. 

Thank you for engaging with the community here for the docs.
