### ISSUE TITLE
Feature: add step by step number to Snip & Sketch app

### ISSUE THREAD

**Issue by xmha97** [MicrosoftDocs/windows-insider#285]
Hello Windows Insider team
Microsoft blocked Iranian access to Feedback Hub app.

![image](https://user-images.githubusercontent.com/23485114/77847600-9cbea780-71d3-11ea-8a0a-810e23a494b0.png)

Now I have suggection for Snip & Sketch app.
Please add step by step number like in shareX app.

![Windows Settings](https://user-images.githubusercontent.com/12841320/64483017-8f33d700-d21b-11e9-9e16-4491cff122ab.png)

Thanks

**Comment by kenwith** [comment]
@xmha97 - thank you for your feedback.
