### ISSUE TITLE
Broken "more information" link

### ISSUE THREAD

**Issue by BR77BE** [MicrosoftDocs/windows-insider#289]
Under "Reset your PC from the cloud";

"For more information, check out [this article from Program Manager Aaron Lower](https://insider.windows.com/articles/optimize-windows-10-pc-reset-using-the-cloud/)."

leads nowhere useful.

Looks like the link is just missing its "en-us" or whatever:

[https://insider.windows.com/en-us/articles/optimize-windows-10-pc-reset-using-the-cloud/](https://insider.windows.com/en-us/articles/optimize-windows-10-pc-reset-using-the-cloud/)

**Comment by mypil** [comment]
@BR77BE - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by BR77BE** [comment]
Sorry, I thought I was commenting directly about this page:

[https://docs.microsoft.com/en-us/windows-insider/at-home/Whats-new-wip-at-home-20h1](https://docs.microsoft.com/en-us/windows-insider/at-home/Whats-new-wip-at-home-20h1)

(But now I don't remember how I arrived here!)

Anyway, that's where the broken link is, as described.

**Comment by mypil** [comment]
@BR77BE - Thank you for pointing this out.

PR #290 has been created to fix and close this issue once the PR is merged.


Thank you and we appreciate your contribution to make the docs better!
