### ISSUE TITLE
What's new for Windows 10 Insider Preview Builds (20H1) incorrect link

### ISSUE THREAD

**Issue by Scottmca** [MicrosoftDocs/windows-insider#291]
https://docs.microsoft.com/en-us/windows-insider/at-home/Whats-new-wip-at-home-20h1#reset-your-pc-from-the-cloud-build-18970

This sentence, the link is invalid
For more information, check out this article from Program Manager Aaron Lower.

Bad Link:  https://insider.windows.com/articles/optimize-windows-10-pc-reset-using-the-cloud/
Correct Link:  https://insider.windows.com/en-us/articles/optimize-windows-10-pc-reset-using-the-cloud/

**Comment by mypil** [comment]
@Scottmca - Thank you for submitting feedback.

This feedback is a duplicate to issue #289 which was resolved by this merged commit https://github.com/MicrosoftDocs/windows-insider/commit/effeda98fa44246dbc7b617741eb1b8405669bf9.

 
Thank you for engaging with the community here to help improve the docs.
