### ISSUE TITLE
Your Phone Updates page stale. No updates since Nov 2020

### ISSUE THREAD

**Issue by ioamnesia** [MicrosoftDocs/windows-insider#300]
https://docs.microsoft.com/en-us/windows-insider/apps/your-phone

**Comment by yogkumgit** [comment]
@bleblancMSFT Please help us in resolving this issue. Thanks

**Comment by riverar** [comment]
@yogkumgit @bleblancMSFT mentioned this page [will be retired](https://twitter.com/brandonleblanc/status/1487214566744281088). Sounds like we can close this issue.
