### ISSUE TITLE
Enabling Windows Insider Page And Services

### ISSUE THREAD

**Issue by intj-t** [MicrosoftDocs/windows-insider#305]
Hi,

I would like to know how to enable the Insider page on Windows Server 1809 standard Sept 2020 Update. I enabled developer mode via group policy. And there are some reports that the page can be enabled via the registry. Put it doesn't work of server
Any Help? I enabled the service.

https://www.howto-connect.com/fix-insider-program-settings-blank-empty-missing-windows-10/

https://www.windowsphoneinfo.com/threads/add-or-remove-windows-insider-program-settings-page-in-windows-10.8061/

https://www.tenforums.com/tutorials/63585-enable-disable-insider-build-settings-windows-10-a.html

These do not work on Server.

**Comment by ItzLevvie** [comment]
Please file a feedback through Feedback Hub about it.

Currently, Windows Server builds don't support receiving preview builds from Windows Update and, therefore, you'll need to upgrade using an ISO image.

**Comment by yogkumgit** [comment]
@bleblancMSFT

**Comment by riverar** [comment]
This repository tracks documentation issues. Doesn't appear this falls into that bucket, so recommend closure @yogkumgit.
