### ISSUE TITLE
Windows Insider changelog is almost always out of date

### ISSUE THREAD

**Issue by CorruptComputer** [MicrosoftDocs/windows-insider#313]
Every time I've looked at this page to check the changelog for the most recent Windows Insider builds it is almost always out of date. At the time of writing the blog only has up to version 21390, while the latest currently available to Insiders is 22533.

Is there no way to automate the publishing of these to ensure the docs are always up to date?

This page: https://docs.microsoft.com/en-us/windows-insider/active-dev-branch
Generated from this file: https://github.com/microsoftdocs/windows-insider/blob/public/wip/Active-Dev-Branch.md

**Comment by riverar** [comment]
There appears to be [pending work](https://twitter.com/brandonleblanc/status/1448391012443844608) so don't think this is something the community could work on / submit a PR for.

@bleblancMSFT Any updated timelines? Thanks!

**Comment by yogkumgit** [comment]
@riverar Thank you very much for the contribution and sharing this explanation. @CorruptComputer Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by CorruptComputer** [comment]
@yogkumgit Why did you close this when the issue isn't fixed? 

The newest build there is a changelog for on that page is still 21390, while the latest Windows Insider build is 22543. This page is STILL out of date.

**Comment by CorruptComputer** [comment]
> If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it.

I honestly can't tell if you are being malicious with this statement or not. Because this sounds like you might be saying that you'll just close any issues I open, similar to this one, without fixing them. 

Can you confirm if this is the case? 
If so, I would like to know why you are so against updating this documentation?

**Comment by riverar** [comment]
I believe this was closed in error. (His closure comment was about this issue, not future issues.)

@yogkumgit Can we keep this one open until the docs are updated? Thanks!
