### ISSUE TITLE
Windows Insider Feedback 4th week of August 2018

### ISSUE THREAD

**Issue by kl07** [MicrosoftDocs/windows-insider#32]
Acknowledgement of the New Feature of Windows Insiders Preview.
I accept to keep using Windows IT Platform for further improvements.
I thank you for issuing this feedback on Github website through your reading and your understanding.

Sincerely,

kl07

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df65515f-272d-53f6-0740-d19784a517f0
* Version Independent ID: 83d9e436-c660-6203-3438-2f75b8b128f4
* Content: [What's new in the Windows 10 Insider Preview Builds (RS5)](https://docs.microsoft.com/en-us/windows-insider/at-home/whats-new-wip-at-home)
* Content Source: [wip/at-home/Whats-new-wip-at-home.md](https://github.com/MicrosoftDocs/windows-insider/blob/master/wip/at-home/Whats-new-wip-at-home.md)
* Service: **wip-at-work**
* GitHub Login: @dawnwood
* Microsoft Alias: **dawn.wood**

**Comment by dawnwood** [comment]
@kl07 Thank you for the comment.
