### ISSUE TITLE
Build 16296 Date and Link

### ISSUE THREAD

**Issue by HaydenHolcomb** [MicrosoftDocs/windows-insider#34]
The release date for Fast Ring should be 9/22/2017. The link also doesn't go to the blog post, it goes back to Flight Hub. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa80910a-e655-34df-d26a-b094dd8702bb
* Version Independent ID: 83b90d10-f455-fee5-cf94-2698f1ac33d6
* Content: [Flight Hub](https://docs.microsoft.com/en-us/windows-insider/flight-hub/#windows-10-april-2018-update-rs4)
* Content Source: [wip/flight-hub/index.md](https://github.com/MicrosoftDocs/windows-insider/blob/master/wip/flight-hub/index.md)
* Service: **wip**
* GitHub Login: @dawnwood
* Microsoft Alias: **dawn.wood**

**Comment by dawnwood** [comment]
Hi @HaydenHolcomb You are correct. I fixed the date and the link in the private docs repo, you should see the change on the live site later this afternoon.
