### ISSUE TITLE
RS2 Builds

### ISSUE THREAD

**Issue by HaydenHolcomb** [MicrosoftDocs/windows-insider#35]
Only one of the builds listed under RS2 is actually from RS2, the rest are from RS5. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa80910a-e655-34df-d26a-b094dd8702bb
* Version Independent ID: 83b90d10-f455-fee5-cf94-2698f1ac33d6
* Content: [Flight Hub](https://docs.microsoft.com/en-us/windows-insider/flight-hub/#windows-10-april-2018-update-rs4)
* Content Source: [wip/flight-hub/index.md](https://github.com/MicrosoftDocs/windows-insider/blob/master/wip/flight-hub/index.md)
* Service: **wip**
* GitHub Login: @dawnwood
* Microsoft Alias: **dawn.wood**

**Comment by dawnwood** [comment]
Thank you @HaydenHolcomb I fixed this copy/paste error and you should see the fix later this afternoon.
