### ISSUE TITLE
Title Typo

### ISSUE THREAD

**Issue by erhuan-msft** [MicrosoftDocs/windows-insider#50]
Acrylicic should be Acrylic

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df65515f-272d-53f6-0740-d19784a517f0
* Version Independent ID: 83d9e436-c660-6203-3438-2f75b8b128f4
* Content: [What's new in the Windows 10 Insider Preview Builds (RS5)](https://docs.microsoft.com/en-us/windows-insider/at-home/whats-new-wip-at-home)
* Content Source: [wip/at-home/Whats-new-wip-at-home.md](https://github.com/MicrosoftDocs/windows-insider/blob/master/wip/at-home/Whats-new-wip-at-home.md)
* Service: **wip-at-work**
* GitHub Login: @dawnwood
* Microsoft Alias: **dawn.wood**

**Comment by dawnwood** [comment]
Thank you, @erhuan-msft I've made that change.
