### ISSUE TITLE
Installing FoD in a container

### ISSUE THREAD

**Issue by cmendible** [MicrosoftDocs/windows-insider#56]
Hi there! 

Current FoD installation requieres a restart after each **DISM** step, and that is something you cannot do in a container scenario.

For instance, in my **dockerfile** I'm running **DISM** commands with the **/NoRestart** flag:

`RUN DISM /Online /Add-Capability /CapabilityName:ServerCore.Appcompatibility~~~~0.0.1.0 /Source:C:/fod /LimitAccess /NoRestart`

or 

`RUN DISM /online /add-package:"Microsoft-Windows-InternetExplorer-Optional-Package~31bf3856ad364e35~amd64~~.cab" /NoRestart`

In any case the capabilities or package remain in Staged, Disabled or Pending State.

Are there plans to support containers?

**Comment by Brentfor** [comment]
Hello, what are you attempting to get working by adding the FOD to a container?  Thanks!

**Comment by cmendible** [comment]
Hi @Brentfor there are at least two scenarios were adding FoD to a container will be helpful:

1. **IE** and **Edge** are needed in containers for selenium tests as you can confirm in the Windows Server User Voice Forum: [Provide an Internet Explorer docker container: enable UI capability](https://windowsserver.uservoice.com/forums/304624-containers/suggestions/17506354-provide-an-internet-explorer-docker-container-ena)
2. Some of my clients have legacy application installers that for some reason verify that **IE** is present as a hard requirement so perhaps FoD will help here too.

Thanks!

**Comment by dawnwood** [comment]
Hi @cmendible Thank you for the feedback. We've heard you. Because this is no longer a documentation issue, I'm closing this thread. To provide product feedback in the future, you might want to go straight to the source by using the "product feedback" button at the bottom of every page on docs.microsoft.com.

**Comment by nagaozen** [comment]
Because there's no "product feedback" at <https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/features-on-demand-v2--capabilities>, I'll post here. I'm the author of a popular Active Server Pages framework, [ASP Xtreme Evolution (AXE)](https://github.com/nagaozen/asp-xtreme-evolution), and we have a hack to leverage node.js npm packages to work inside our environment <https://github.com/nagaozen/evolved-npm2asp-bundler>.

I evaluated the Windows Server 2019 DE and the ServerCore (with FoD) on a virtual machine and they both support this trick. But we are trying to move into a container strategy and installing FoD on the <mcr.microsoft.com/windows/servercore:ltsc2019> seems impossible for the reasons already explained in this issue #56.

```ps
Capability Identity : ServerCore.AppCompatibility~~~~0.0.1.0
State : Staged
```

I made a diff between the servercore vm and container servers:

```diff
0a1
> AcGenral.dll
2a4,5
> AcSpecfc.dll
> ActivationManager.dll
8a12
> admwprox.dll
18a23
> ahadmin.dll
19a25,26
> ApiSetHost.AppExecutionAlias.dll
> AppContracts.dll
23a31
> AppResolver.dll
25a34
> aspperf.dll
28a38,40
> AudioEng.dll
> AUDIOKSE.dll
> AudioSes.dll
33a46,48
> AuthFWGP.dll
> AuthFWSnapin.dll
> AuthFWWizFwk.dll
35a51,53
> avicap32.dll
> avifil32.dll
> avrt.dll
45a64,65
> biwinrt.dll
> BluetoothApis.dll
49a70
> capauthz.dll
55a77
> cdp.dll
66a89,91
> Chakra.dll
> Chakradiag.dll
> Chakrathunk.dll
68a94
> cic.dll
71a98
> cldapi.dll
73a101
> ClipboardServer.dll
75a104
> cmcfg32.dll
76a106
> cmdial32.dll
77a108,111
> cmlua.dll
> cmpbk32.dll
> cmstplua.dll
> cmutil.dll
78a113
> cngkeyhelper.dll
82a118
> colorui.dll
94a131,132
> CoreUIComponents.dll
> CPrepSrv.dll
106a145
> cryptngc.dll
118a158,164
> d2d1.dll
> d3d10.dll
> d3d10core.dll
> d3d10level9.dll
> d3d10warp.dll
> d3d10_1.dll
> d3d10_1core.dll
123a170
> d3d9on12.dll
124a172
> D3DSCache.dll
125a174,175
> DataExchange.dll
> davclnt.dll
133a184
> dcomp.dll
134a186,188
> devenum.dll
> deviceaccess.dll
> deviceassociation.dll
135a190,191
> DevicePairingProxy.dll
> devmgr.dll
148a205,207
> dinput.dll
> dinput8.dll
> Direct2DDesktop.dll
151a211,220
> dmdlgs.dll
> dmdskmgr.dll
> dmdskres.dll
> dmdskres2.dll
> dmenrollengine.dll
> dmintf.dll
> dmocx.dll
> dmprocessxmlfiltered.dll
> dmutil.dll
> dmvdsitf.dll
159a229
> dsdmo.dll
160a231
> dsound.dll
162a234
> dsreg.dll
166a239
> dtsh.dll
168a242
> dusmapi.dll
169a244
> dwmcore.dll
170a246
> DXCaptureReplay.dll
171a248,254
> dxilconv.dll
> dxtmsft.dll
> DXToolsMonitor.dll
> DXToolsOfflineAnalysis.dll
> DXToolsReporting.dll
> dxtrans.dll
> dxva2.dll
176a260,261
> easwrt.dll
> edgehtml.dll
177a263,267
> EdgeManager.dll
> EditBufferTestHook.dll
> edpauditapi.dll
> edputil.dll
> efsadu.dll
179a270,275
> efswrt.dll
> els.dll
> ELSCore.dll
> elshyph.dll
> elsTrans.dll
> embeddedmodesvcapi.dll
180a277
> enrollmentapi.dll
188a286,287
> ExecModelClient.dll
> ExplorerFrame.dll
190a290
> FcSrv_ps.dll
199a300
> FSClient.dll
208a310
> gcdef.dll
210a313,315
> glmf32.dll
> GlobCollationHost.dll
> glu32.dll
216a322,323
> HelpPaneProxy.dll
> hhsetup.dll
218a326,328
> hlink.dll
> hnetcfg.dll
> HrtfApo.dll
219a330
> htui.dll
221a333
> icmui.dll
222a335,343
> IDStore.dll
> IEAdvpack.dll
> ieapfltr.dll
> iedkcs32.dll
> ieframe.dll
> iemigplugin.dll
> iepeers.dll
> ieproxy.dll
> iernonce.dll
223a345,347
> iesetup.dll
> iesysprep.dll
> ieui.dll
226a351,352
> iisrstap.dll
> iisRtl.dll
228a355,356
> imapi2fs.dll
> imgutil.dll
229a358,359
> IndexedDbLegacy.dll
> inetcomm.dll
230a361,362
> INETRES.dll
> InkObjCore.dll
231a364
> InputHost.dll
232a366,367
> inseng.dll
> Interop.DfsrHelper.dll
236a372,373
> ipsecsnp.dll
> ipsmsnap.dll
241a379,381
> itircl.dll
> itss.dll
> JavaScriptCollectionAgent.dll
244a385,386
> jscript9.dll
> jscript9diag.dll
457a600
> ksuser.dll
459a603
> LicenseManagerApi.dll
460a605
> licmgr10.dll
462a608,609
> localsec.dll
> loghours.dll
467a615,620
> Magnification.dll
> mapi32.dll
> mapistub.dll
> mciavi32.dll
> mdmlocalmanagement.dll
> mdmregistration.dll
471a625,626
> mfksproxy.dll
> mfsensorgroup.dll
475a631
> MicrosoftAccountTokenProvider.dll
476a633
> miguiresource.dll
480a638
> MirrorDrvCompat.dll
483a642,644
> mmcbase.dll
> mmcndmgr.dll
> mmcshext.dll
489a651
> mprsnap.dll
490a653
> msacm32.dll
491a655
> MSAJApi.dll
509a674
> msdmo.dll
514a680,681
> msfeeds.dll
> msfeedsbs.dll
515a683,686
> mshtml.dll
> MshtmlDac.dll
> mshtmled.dll
> mshtmler.dll
530a702
> msoert2.dll
534a707,708
> msrating.dll
> msrle32.dll
547a722,723
> msvfw32.dll
> msvidc32.dll
561a738
> mydocs.dll
568a746
> nddeapi.dll
586a765
> netplwiz.dll
592a772
> netshell.dll
593a774
> NetworkCollectionAgent.dll
596a778
> nfsclusrc.dll
621a804
> occache.dll
645a829
> oledlg.dll
646a831
> OnDemandBrokerClient.dll
649a835,836
> onex.dll
> onexui.dll
651a839
> opengl32.dll
653a842,843
> P2PGraph.dll
> packager.dll
655a846,847
> pcacli.dll
> pcaui.dll
658a851
> pdhui.dll
664a858,859
> PhotoMetadataHandler.dll
> pid.dll
667a863,864
> pngfilt.dll
> policymanager.dll
671a869,871
> Print.Workflow.Source.dll
> PrintWorkflowProxy.dll
> PrintWorkflowService.dll
681a882
> quartz.dll
683a885
> rasadhlp.dll
686a889
> rassfm.dll
687a891
> rasuser.dll
696a901,902
> remoteaudioendpoint.dll
> ResourcePolicyClient.dll
698a905
> rgb9rast.dll
700a908,909
> rmclient.dll
> rometadata.dll
709a919
> rtrfiltr.dll
713a924,925
> sas.dll
> scansetting.dll
731a944,947
> SensorsApi.dll
> SensorsNativeApi.dll
> SensorsNativeApi.V2.dll
> SensorsUtilsV2.dll
732a949
> SettingSyncCore.dll
737a955
> ShareHost.dll
738a957
> shdocvw.dll
742a962
> shpafact.dll
743a964
> shunimpl.dll
752a974
> SpatializerApo.dll
777a1000,1001
> ssdm.dll
> ssdpapi.dll
780a1005,1006
> sti.dll
> StorageUsage.dll
786a1013,1014
> SystemEventsBrokerClient.dll
> t2embed.dll
792a1021,1022
> TempSignedLicenseExchangeTask.dll
> TextInputFramework.dll
805a1036
> twinui.appcore.dll
812a1044,1045
> UiaManager.dll
> UIAnimation.dll
820a1054
> url.dll
823a1058,1059
> UserDeviceRegistration.dll
> UserDeviceRegistration.Ngc.dll
840a1077,1078
> VsGraphicsCapture.dll
> VsGraphicsExperiment.dll
844a1083
> wamregps.dll
845a1085,1086
> wcmapi.dll
> wdc.dll
848a1090,1091
> webcheck.dll
> WebClnt.dll
849a1093
> webplatstorageserver.dll
859a1104
> wfdprov.dll
860a1106,1109
> wiadefui.dll
> wiascanprofiles.dll
> wiashext.dll
> wiatrace.dll
868a1118,1119
> Windows.ApplicationModel.Background.SystemEventsBroker.dll
> Windows.Data.Pdf.dll
869a1121,1122
> Windows.Gaming.Input.dll
> Windows.Globalization.dll
870a1124,1126
> Windows.Graphics.Printing.Workflow.dll
> Windows.Graphics.Printing.Workflow.Native.dll
> Windows.Internal.SecurityMitigationsBroker.dll
872a1129,1133
> Windows.Networking.dll
> Windows.Networking.HostName.dll
> Windows.Networking.Proximity.dll
> Windows.Security.Integrity.dll
> Windows.Shell.ServiceHostBuilder.dll
874a1136
> Windows.System.Launcher.dll
875a1138
> Windows.UI.Core.TextInput.dll
876a1140
> Windows.UI.dll
877a1142
> WindowsCodecsExt.dll
896a1162
> winshfhc.dll
905a1172,1174
> wlanapi.dll
> wlanhlp.dll
> wlanui.dll
907a1177
> wlidprov.dll
911a1182
> WMPhoto.dll
913a1185
> WordBreakers.dll
916a1189
> WSClient.dll
917a1191,1192
> wsdchngr.dll
> wshbth.dll
940a1216
> wuceffects.dll
942a1219,1224
> wvc.dll
> XAudio2_8.dll
> XAudio2_9.dll
> XInput1_4.dll
> XInput9_1_0.dll
> XInputUap.dll
```

It shows that many required `dll`s needed to work —like msshtml.dll, jscript9.dll, chakra.dll _et cetera_— are unavailable inside the container. I'm sending an attachment with coverage tests to help evaluating the server.

[tests.zip](https://github.com/MicrosoftDocs/windows-insider/files/2966573/tests.zip)

**Comment by Brentfor** [comment]
Adding Vinicius Apolinario as I believe he has recently worked with the App Compatibility FOD in containers.

Vinicius, did you add the FOD with DISM /online or DISM /offline?

**Comment by Brentfor** [comment]
/online. I followed the documentation here: https://docs.microsoft.com/en-us/windows-server/get-started-19/install-fod-19
See that I installed on the Server Core container host, not the container itself.
V

From: Brent Forman <brentf@microsoft.com>
Sent: Thursday, March 14, 2019 10:28 AM
To: MicrosoftDocs/windows-insider <reply@reply.github.com>; MicrosoftDocs/windows-insider <windows-insider@noreply.github.com>; Vinicius Apolinario <Vinicius.Apolinario@microsoft.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [MicrosoftDocs/windows-insider] Installing FoD in a container (#56)

Adding Vinicius Apolinario as I believe he has recently worked with the App Compatibility FOD in containers.

Vinicius, did you add the FOD with DISM /online or DISM /offline?

**Comment by nagaozen** [comment]
> /online. I followed the documentation here: https://docs.microsoft.com/en-us/windows-server/get-started-19/install-fod-19 See that I installed on the Server Core container host, not the container itself. V

Does it mean that installing FoD on the host will make it available in the container too? I'm confused, it doesn't work in my environment. We are asking for the FoD on the container itself.

**Comment by cmendible** [comment]
As stated by @nagaozen we need FoD inside a container not in the host....

**Comment by Brentfor** [comment]
Although we are working to get more clarity, at this time we don’t believe FODs are supported in containers.  Sounds like having the App Compatibility FOD in Server Core containers is very desirable?

Thanks,
Brent

**Comment by nagaozen** [comment]
@Brentfor it's very desirable.

**Comment by nagaozen** [comment]
Any news on this issue?!

**Comment by gboy13** [comment]
Was this ever resolved?

**Comment by nagaozen** [comment]
> Was this ever resolved?

Nopz

**Comment by edc1934** [comment]
> 

RUN copy-item C:/TXE/DLL/expsrv.dll C:/Windows/SysWOW64; `
	copy-item C:/TXE/DLL/vbajet32.dll C:/Windows/SysWOW64;
