### ISSUE TITLE
Windows IOT Updates are not listed promptly

### ISSUE THREAD

**Issue by alvinchen1** [MicrosoftDocs/windows-insider#58]
As of 9/23/2018, Windows 10 IOT October 2018 Update (RS5) released build 17763 released for Insiders.  See https://social.msdn.microsoft.com/Forums/en-US/cfb8cb1c-cecc-4116-aed1-c7a002464dcf/new-flight-17763-released-for-insiders?forum=WindowsIoT

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa80910a-e655-34df-d26a-b094dd8702bb
* Version Independent ID: 83b90d10-f455-fee5-cf94-2698f1ac33d6
* Content: [Flight Hub](https://docs.microsoft.com/en-us/windows-insider/flight-hub/)
* Content Source: [wip/flight-hub/index.md](https://github.com/MicrosoftDocs/windows-insider/blob/master/wip/flight-hub/index.md)
* Service: **wip**
* GitHub Login: @dawnwood
* Microsoft Alias: **dawn.wood**

**Comment by dawnwood** [comment]
Hi @alvinchen1 Thank you for noticing this. I've updated the table and it will be live soon.
Best,
Dawn
