### ISSUE TITLE
Missing headers for Failover Cluster NTLM and Shielded VM changes

### ISSUE THREAD

**Issue by orindlt** [MicrosoftDocs/windows-insider#7]
After Windows Defender Application Control there should be headers for "Failover Cluster removing use of NTLM authentication" and "Shielded virtual machines – Offline mode, VMConnect and Linux support" as these are also clearly separate sections of the document (which should also be present in the index at the top of the document)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30f7de7e-c8cd-793d-6fb8-3345824f5914
* Version Independent ID: 4ea62ad0-9a4d-1456-be70-22a9a3f614fa
* Content: [What's new in the Windows Server 2019 Insider Preview Builds](https://docs.microsoft.com/en-us/windows-insider/at-work/whats-new-wip-at-work)
* Content Source: [wip/at-work/Whats-new-wip-at-work.md](https://github.com/MicrosoftDocs/windows-insider/blob/master/wip/at-work/Whats-new-wip-at-work.md)
* Service: **wip-at-work**
* GitHub Login: @dawn.wood
* Microsoft Alias: **dawn.wood**

**Comment by dawnwood** [comment]
Nice catch! This is fixed and propped to the live server now. thanks!
