### ISSUE TITLE
Copy/Paste Issue?

### ISSUE THREAD

**Issue by bkpearson** [MicrosoftDocs/windows-insider#70]
I know RS5 just went out but should the text below the "Next feature update for Windows 10 (19H1)" header be changed? It still mentions RS5.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa80910a-e655-34df-d26a-b094dd8702bb
* Version Independent ID: 83b90d10-f455-fee5-cf94-2698f1ac33d6
* Content: [Flight Hub](https://docs.microsoft.com/en-us/windows-insider/flight-hub/)
* Content Source: [wip/flight-hub/index.md](https://github.com/MicrosoftDocs/windows-insider/blob/master/wip/flight-hub/index.md)
* Service: **wip**
* GitHub Login: @dawnwood
* Microsoft Alias: **dawn.wood**

**Comment by dawnwood** [comment]
Hey @bkpearson You are right!! I made the fix and thank you for noticing.
Best,
Dawn
