### ISSUE TITLE
18282 is not listed in 19H1 section

### ISSUE THREAD

**Issue by KB4284848** [MicrosoftDocs/windows-insider#81]
https://blogs.windows.com/windowsexperience/2018/11/14/announcing-windows-10-insider-preview-build-18282

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa80910a-e655-34df-d26a-b094dd8702bb
* Version Independent ID: 83b90d10-f455-fee5-cf94-2698f1ac33d6
* Content: [Flight Hub](https://docs.microsoft.com/en-us/windows-insider/flight-hub/)
* Content Source: [wip/flight-hub/index.md](https://github.com/MicrosoftDocs/windows-insider/blob/master/wip/flight-hub/index.md)
* Service: **wip**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by KB4284848** [comment]
Closing issue since Flight Hub has been updated to add 18282 and 18290

**Comment by KexyBiscuit** [comment]
And this repo is no longer up-to-date.
