### ISSUE TITLE
Please fix metro app running in background Windows 10 

### ISSUE THREAD

**Issue by kennethyha** [MicrosoftDocs/windows-insider#86]
Metro apps such as calculator and Microsoft Edge still run in background and randomly starts itself although background apps in settings is toggled off. This need to be fixed because random waking up of apps causes inconsistent fps in games which affects the competitive gameplay experience. Please fix that before moving snipping tools to store. Keep up the good work!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92ba811c-665d-1fb0-570c-8abf7a321544
* Version Independent ID: dbebf3ff-c935-6903-1d26-da24d743387f
* Content: [New and updated apps in the Windows 10 Insider Preview Builds (19H1)](https://docs.microsoft.com/en-us/windows-insider/at-home/whats-new-apps#sticky-notes)
* Content Source: [wip/at-home/whats-new-apps.md](https://github.com/MicrosoftDocs/windows-insider/blob/master/wip/at-home/whats-new-apps.md)
* Service: **wip-at-home**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by ItzLevvie** [comment]
@kennethyha Please report such issue in the Feedback Hub.

This GitHub repository focuses on the technical documentation of the Windows Insider Program and therefore any issues reported on Windows 10 in GitHub will be ignored by the team

**Comment by kennethyha** [comment]
Hi sir, thanks for reply. I reported many times since Windows 10 is still
in beta phase, not released yet, but it seems the problem still persists in
the build I am using now 17763. Can you please help to notify the developer
team? Thanks in advance.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@kennethyha - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback on how to make the Windows Insider Program better. They keep a close tab on user feedback and it would be awesome if you could add your voice in User Voice **https://insider.windows.com/en-us/how-to-feedback/#submit-feedback-on-behalf-of-your-organization**
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
