### ISSUE TITLE
misspelling

### ISSUE THREAD

**Issue by midnight2105** [MicrosoftDocs/windows-insider#90]
Line 5 I think yoru is supposed to be your
You can register with either yoru work account in Azure Active Directory or your Microsoft account.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4b123d9-739d-729e-378c-b2eeb88ad8f0
* Version Independent ID: cfe614e9-a2f7-aa3e-e075-afecad232df6
* Content: [Register for the Windows 10 Insider Program for Business](https://docs.microsoft.com/en-us/windows-insider/at-work-pro/wip-4-biz-register)
* Content Source: [wip/at-work-pro/wip-4-biz-register.md](https://github.com/MicrosoftDocs/windows-insider/blob/master/wip/at-work-pro/wip-4-biz-register.md)
* Service: **wip-at-work-pro**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by lizap** [comment]
Yep, should have been "your." Fixing now -thanks!
