### ISSUE TITLE
RS4 table has vertical borders

### ISSUE THREAD

**Issue by Rahsna** [MicrosoftDocs/windows-insider#91]
Judging on the design of the remaining tables, it looks like the table of RS4 have vertical borders, which none of the other tables have. I assume it is an oversight in the table design 🙂
As a side effect, this adds a horizontal scrollbar to that table.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa80910a-e655-34df-d26a-b094dd8702bb
* Version Independent ID: 83b90d10-f455-fee5-cf94-2698f1ac33d6
* Content: [Flight Hub](https://docs.microsoft.com/en-us/windows-insider/flight-hub/)
* Content Source: [wip/flight-hub/index.md](https://github.com/MicrosoftDocs/windows-insider/blob/master/wip/flight-hub/index.md)
* Service: **wip**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by lizap** [comment]
Hi, this is related to how big the table is on your display - try zooming in or out, and you'll see different borders on the table. Because this is part of the default behavior of the site, it's not something that we control - as such, I'm going to close this issue. Thanks!
