### ISSUE TITLE
Table of contents links

### ISSUE THREAD

**Issue by HaydenHolcomb** [MicrosoftDocs/windows-insider#92]
In the table of contents on the left, there are two links that are incorrect. 
1. "What's new for Windows 10 Insider Preview Builds" links to https://docs.microsoft.com/en-us/windows-insider/at-home/whats-new-at-home which gives a 404 error. The link should be https://docs.microsoft.com/en-us/windows-insider/at-home/whats-new-wip-at-home
2. "What was new for Windows 10, version 1809" links to https://docs.microsoft.com/en-us/windows-insider/at-home/whats-new-at-home-1809 which also gives a 404 error. The link should be https://docs.microsoft.com/en-us/windows-insider/at-home/whats-new-wip-at-home-1809

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa80910a-e655-34df-d26a-b094dd8702bb
* Version Independent ID: 83b90d10-f455-fee5-cf94-2698f1ac33d6
* Content: [Flight Hub](https://docs.microsoft.com/en-us/windows-insider/flight-hub/)
* Content Source: [wip/flight-hub/index.md](https://github.com/MicrosoftDocs/windows-insider/blob/master/wip/flight-hub/index.md)
* Service: **wip**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by HaydenHolcomb** [comment]
Looking at the source on GitHub, the links appear to be correct (MicrosoftDocs/windows-insider/wip/flight-hub/TOC.md). But when using Inspect Element in a browser, the href link there is incorrect.

**Comment by BR77BE** [comment]
Why no announcements for Release Preview ring?

**Comment by lizap** [comment]
Thanks for flagging the issue - I've fixed the TOC links. Thanks!
