### ISSUE TITLE
Dark theme in File Explore

### ISSUE THREAD

**Issue by BR77BE** [MicrosoftDocs/windows-insider#93]
ExploreR

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc12e690-19c5-ba46-530f-56b2e4f2bb33
* Version Independent ID: 237aec15-eb8f-78ed-086f-518b4ce554dd
* Content: [What's new in the Windows 10 Insider Preview Builds (RS5)](https://docs.microsoft.com/en-us/windows-insider/at-home/whats-new-wip-at-home-1809)
* Content Source: [wip/at-home/Whats-new-wip-at-home-1809.md](https://github.com/MicrosoftDocs/windows-insider/blob/master/wip/at-home/Whats-new-wip-at-home-1809.md)
* Service: **wip-at-home**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@BR77BE - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
