### ISSUE TITLE
Documentation shows git conflicts

### ISSUE THREAD

**Issue by tip2tail** [MicrosoftDocs/windows-insider#94]
The documentation at https://docs.microsoft.com/en-gb/windows-insider/at-home/whats-new-wip-at-home is showing a number of Git conflict markers and commit IDs throughout it.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df65515f-272d-53f6-0740-d19784a517f0
* Version Independent ID: 83d9e436-c660-6203-3438-2f75b8b128f4
* Content: [What's new in the Windows 10 Insider Preview Builds (19H1)](https://docs.microsoft.com/en-gb/windows-insider/at-home/whats-new-wip-at-home#notepad-updates-build-18298)
* Content Source: [wip/at-home/Whats-new-wip-at-home.md](https://github.com/MicrosoftDocs/windows-insider/blob/master/wip/at-home/Whats-new-wip-at-home.md)
* Service: **wip-at-home**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by drewswaycool** [comment]
It did provide a good laugh however..

**Comment by tip2tail** [comment]
@lizap - I see that this has now been fixed :)

**Comment by lizap** [comment]
Merge conflicts are my plague in this content set. Thanks for flagging it! Please - keep doing so!
