### ISSUE TITLE
Indic Phonetic keyboards now available for PC - gif - It isn't anim gif

### ISSUE THREAD

**Issue by hNczy** [MicrosoftDocs/windows-insider#95]
Actuially in the article https://docs.microsoft.com/en-us/windows-insider/at-home/whats-new-wip-at-home#notepad-updates-build-18298 - in the block `Indic Phonetic keyboards now available for PC` - the referenced animation gif: https://docs.microsoft.com/en-us/windows-insider/at-home/images/18272-image3.gif is not an animation.

From the article:
> For example, if you typed "namaste" using the Hindi Phonetic keyboard we would suggest नमस्ते, as you can see in the below gif:

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@hNczy - Thank you for submitting feedback.

I checked on the article and could not find the portion that you are referring to so it is possible that it may have been removed by the doc owner. Can you please check again and let me know which portion of the article should be edited and/or included?

**Comment by mypil** [comment]
@hNczy - I would like to follow up on this. Do you have any updates?

**Comment by hNczy** [comment]
Yes. I checked again the article. I do not find this portion. I also think it was removed. Thank you!

**Comment by mypil** [comment]
@officedocsbot close
