### ISSUE TITLE
download PDF link result in empty file

### ISSUE THREAD

**Issue by lbmonsalve** [MicrosoftDocs/windows-insider#96]
when I click in "download PDF" link at left-bottom of page (https://docs.microsoft.com/en-us/windows-insider/at-home/whats-new-wip-at-home#introducing-windows-sandbox-build-18305) the output file is empty.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df65515f-272d-53f6-0740-d19784a517f0
* Version Independent ID: 83d9e436-c660-6203-3438-2f75b8b128f4
* Content: [What's new in the Windows 10 Insider Preview Builds (19H1)](https://docs.microsoft.com/en-us/windows-insider/at-home/whats-new-wip-at-home#introducing-windows-sandbox-build-18305)
* Content Source: [wip/at-home/Whats-new-wip-at-home.md](https://github.com/MicrosoftDocs/windows-insider/blob/master/wip/at-home/Whats-new-wip-at-home.md)
* Service: **wip-at-home**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@lbmonsalve - Thank you for pointing this out.

I will get this issue over to the Windows Insider writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@lizap - I checked on the Download link and it redirects to a page with a message-"Error
Failed to load PDF document." Here's the Download link URL - [](https://opdhsblobprod04.blob.core.windows.net/contents/8bbef6de52cc41879cccbe6cf3d0ddab/d98c1dd4008f04b2e9800998ecf8427e?sv=2015-04-05&sr=b&sig=%2F0o3wAQ7EFLXUaDWP4Qjd9lwzW%2FmTOtI8Q7LJ2NSomA%3D&st=2019-03-19T18%3A38%3A09Z&se=2019-03-20T18%3A48%3A09Z&sp=r)

Please let us know what is the correct URL link for this so a PR can be created for or please advise on how to proceed with this. Thank you.

**Comment by mypil** [comment]
@lizap - I would like to follow up on this. Do you have any updates.

**Comment by mypil** [comment]
@lizap - I would like to follow up on this. Any updates?

**Comment by mypil** [comment]
@lbmonsalve - From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
