### ISSUE TITLE
All this "whats new for insiders" is great, but

### ISSUE THREAD

**Issue by bjthomson** [MicrosoftDocs/windows-insider#97]
It would be really handy to have a final, polished version for end-users available after an update, otherwise, its a case of "hunt the changes", and "oo look what I just found". When I updated last time, I did see a screen with some tips, but it went away, and now I cant find it. 
Make it a web page, and leave a shortcut on the desktop + in my inbox + on the start menu, etc etc. 

I've said many times: documentation should be based on what you want to do, rather than what a button does.

(I'm still waiting for 1809 BTW)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df65515f-272d-53f6-0740-d19784a517f0
* Version Independent ID: 83d9e436-c660-6203-3438-2f75b8b128f4
* Content: [What's new in the Windows 10 Insider Preview Builds (19H1)](https://docs.microsoft.com/en-gb/windows-insider/at-home/whats-new-wip-at-home)
* Content Source: [wip/at-home/Whats-new-wip-at-home.md](https://github.com/MicrosoftDocs/windows-insider/blob/master/wip/at-home/Whats-new-wip-at-home.md)
* Service: **wip-at-home**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by pownas** [comment]
Here are the link to Windows IT-Pro docs where you can find all polished versions:
https://docs.microsoft.com/en-us/windows/whats-new/

Tips: 
1. Go to docs.com
2. Click on “Windows”
3. Under “Windows documentation”-title, press on “Developer” to show a drop down-list (not so visible tho...) , and switch to: “IT-Pro”. There you will find a lot of Windows pro user documentation.

**Comment by bjthomson** [comment]
I didn't see this till today. My original post was relating to *end-user* documentation, not IT pros or developers.

Oh Well.
