### ISSUE TITLE
Prevent WakeUp

### ISSUE THREAD

**Issue by UnityUser** [MicrosoftDocs/windows-insider#98]
There are a lot of reasons TURN OFF computer WakeUp - for example, I don't want to get up in the middle of the night because of my PC is lighting like New Year's tree. 
Please add a feature COMPLETELY turn OFF wake up from hibernation. Critical Updates or not - it does not matter. I will spend my time when I turn my computer on and will wait for the updates installed. But I will be MY decision!
Thank you.

**Comment by lizap** [comment]
The best way to get this feedback heard is to submit it through the Feedback Hub on Windows 10. Thanks!
